### ISSUE TITLE
No results in Existing_variation, CLIN_SIG, AF columns

### ISSUE THREAD

**Issue by sean-ocall** [Ensembl/ensembl-vep#1007]
I've installed vep-104 along with the [homo sapiens GRCh37 cache file](http://ftp.ensembl.org/pub/release-96/variation/indexed_vep_cache/homo_sapiens_vep_96_GRCh37.tar.gz) and [fasta file](http://ftp.ensembl.org/pub/grch37/release-96/fasta/homo_sapiens/dna/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz).

I'm running with the following commands: 
`vep -i $TSV_NAME -v --dir_cache $PWD --cache --offline --format ensembl --fasta $PWD/Homo_sapiens.GRCh37.dna.primary_assembly.fa --variant_class --sift b --polyphen b --regulatory --total_length --numbers --no_escape --hgvs --hgvsg --shift_hgvs 0 --symbol --ccds --uniprot --protein --canonical --biotype --domains --xref_refseq --check_existing --exclude_null_alleles --af --af_1kg --af_gnomad --tab -o vep_output.tsv`

I get most of the columns I require in the output, but the three I've mentioned in the heading: Existing_variation, CLIN_SIG, AF and other AF columns, as well as gnomAD_AF columns are null for all variants. I've run some of my data on VEP on grch37.ensembl.org and these columns do return values when run there. 

Is there some cache file that I'm missing from my installation? Any tips for troubleshooting this as I've hit a brick wall with it.

single row from my input file: 
`1  1722003  1722003  G/A  +  1_1722003_G_A`

Thanks,
Sean

**Comment by sean-ocall** [comment]
As a followup, I've tried the same with vep version 96 and I get data for these columns with v96. I note that the homo_sapiens cache file for v96 is ~20Gb, while v104 is ~14Gb. Is there a supplementary cache file I am missing?

**Comment by at7** [comment]
Hello,
I'm going to take a look at this issue today and let you know as soon as I know more.

Best wishes,
Anja

**Comment by at7** [comment]
Hi Sean,
I was able to annotate the example variant 1_1722003_G_A with the 104 GRCh37 cache files. I wonder if unpacking the cache files didn't work correctly. Could you please check in your cache directory if you can find this file: PATH_TO_CACHE_DIR/homo_sapiens/104_GRCh37/1/all_vars.gz?

The cache size difference is expected and related to adding new regulation data into 96 which then from subsequent releases has been more refined and reduced in size again.

Thank you,
Anja

**Comment by sean-ocall** [comment]
Hi, yes I can see that as a 684Mb file in my cache directory. Just to be clear - I can annotate the variants, just not with _all_ of the information I require. Do you see data in the Existing_variation column in your annotation?

I've also tried the 104_merged version of the cache, with the same result. Checksums are correct for both of the caches I have tried and all_vars.gz seems to be present everywhere it should be

**Comment by at7** [comment]
Hi, thank you for checking. The missing annotations (existing variation, allele frequencies, ...) come from the cache file. And it looks like as if there is a problem retrieving the data from the cache files. The size of PATH_TO_CACHE_DIR/homo_sapiens/104_GRCh37/1/all_vars.gz is the same as for my file.
There is a possibility that the way we created the index is causing problems for you. We use tabix to retrieve annotations from the cache file by location. Could you please run `tabix PATH_TO_CACHE_DIR/homo_sapiens/104_GRCh37/1/all_vars.gz 1:1722003-1722003` and see if it returns the annotations?

Thank you,
Anja

**Comment by sean-ocall** [comment]
output is:
`[tabix] failed to load the index file.`

I guess we've found the problem. Is it the version of tabix?:
`Program: tabix (TAB-delimited file InderXer)
Version: 0.2.5 (r1005)`

**Comment by at7** [comment]
The indexed cache files require Bio::DB::HTS (which is setup by INSTALL.pl) or tabix. VEP will check first if it can use the tabix utility that is part of Bio::DB::HTS and if that is not available use the tabix tool which it tries to identify with `which tabix`. In my command above I was using tabix version [1.3.1](https://github.com/samtools/samtools/tags). 

Have you installed VEP with the INSTALL.pl script, and do you know if you have also installed Bio::DB::HTS as part of it?

There is also the option of downloading the non-indexed cache files and then index the cache files using this [script](https://github.com/Ensembl/ensembl-vep/blob/release/104/convert_cache.pl). The script will use your version of tabix which should then prevent the error which we see now. I think the error is caused by a version incompatibility of the tabix tool.

[Here](https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache) is more documentation on the cache file installation.

**Comment by sean-ocall** [comment]
Thanks for your help with this. Moving to tabix v1.3.1 solves this completely. I was just using too old a version. 

Cheers!
