### ISSUE TITLE
grch37 and vep104 contains all the databse annotation

### ISSUE THREAD

**Issue by worker000000** [Ensembl/ensembl-vep#1011]
Thanks a lot for making vep more and more completed
grch37 and vep104

http://ftp.ensembl.org/pub/grch37/release-104/variation/vep/
does cache data here has all the database annotation needed as mentioned here,  and will it annotate all the database like gnomad sift automatically?
![image](https://user-images.githubusercontent.com/25199946/122957788-db321a80-d3b4-11eb-995e-215bd678a81b.png)
#
# 
can vep specify the transcript by user defined input file, though it supplied the canonical and pick argument

**Comment by helensch** [comment]
Hi @worker000000 

Information on the VEP caches is available at:
http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache

It describes the data in the cache, as shown in the diagram you provided

See also:
https://www.ensembl.info/2020/10/23/cool-stuff-ensembl-vep-can-do-whats-in-the-cache-and-how-does-vep-use-it/

We recommend using an indexed cache
GRCh37: http://ftp.ensembl.org/pub/grch37/release-104/variation/indexed_vep_cache/
GRCh38: http://ftp.ensembl.org/pub/release-104/variation/indexed_vep_cache/

There are 3 types of cache file 
 - one with the Ensembl transcripts (the default)
 - a refseq one with the RefSeq transcripts
 - a merged one that contains both.

For information on running VEP see:
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html

To run VEP with default options and the cache, use the following command:
 ./vep --cache -i input.txt -o output.txt 

Use VEP options to include other information from the cache
http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#output

e.g. use --af_gnomad
to include allele frequency from Genome Aggregation Database (gnomAD)
http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_af_gnomad

For VEP output, that includes transcript see:
https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#output

For filtering results
https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html

For summarising annotation see
https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick

I hope that helps. Please let me know if you have any further queries.

Regards
Helen

**Comment by worker000000** [comment]
Thanks a lot. vep can get the right hgvs,but annovatr not
I have already reads these useful links, after each time read, more helpful.
But I still want to ask some question.
#
1 though vep offers argument pick to select the variant, can I offer a self-defined wanted transcript for each gene?
# 
2 annote sppeed is really not that fast, though I have add argument **--no_stats**, annotate 40000 variants takes 1.5h on a 500g memory and 100 cpu server

command like

docker run --rm --user `id -u`:`id -g` -v /home/DATA/kobe:/data docker.io/ensemblorg/ensembl-vep vep --input_file /data/t.vardict.vcf  --output_file /data/t_no_stats.vep.vcf --dir_cache /data/database/anno/vep104  --dir_plugins /data/database/anno/vep104/VEP_plugins-release-104 --fasta /data/database/anno/vep104/Homo_sapiens.GRCh37.dna.primary_assembly_chr.fa --offline  --cache  --transcript_version   --force_overwrite --transcript_version --refseq --assembly GRCh37 --format vcf --cache_version 104 --keep_csq  --variant_class  --vcf --pick --sift b  --polyphen b --ccds --hgvs  --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot  --appris --gene_phenotype --af --af_1kg --af_esp --af_gnomad --max_af --pubmed --var_synonyms --variant_class --no_stats
# 
vep output two kind of output , vcf or tab, but can not generate once time, and the tab version does not keep the origin information of vardict caller outoput, for eaxmple, strings  STATUS=LikelySomatic;SAMPLE=L2007450 missed in the tab version but exists in vcf version

**Comment by helensch** [comment]
Hi @worker000000 

Thank you for your queries. I have provided information below.

**1) Transcript selection**

Filtering by transcript can be done when running VEP.
https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#filt

See `--transcript_filter` option

NOTE: This will filter your results before they are written to
your output file. Using VEP's filtering script, it is possible to filter your
results after VEP has run. This way you can retain all of the results and run
multiple filter sets on the same results to find different data of interest. 

`filter_vep` can be used to filter transcripts

https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html

From the example:
 match entries where Feature (Transcript) is "ENST00000307301"
`--filter "Feature is ENST00000307301"`

If you have a list of transcripts that you wish to select from a VEP output file a
script or utility such as grep could be used.

**2) VEP run times**

The time taken to run VEP depends on the options selected.
`--regulatory `option will increase runtime due to the large amount of regulatory data available

The following page provides steps that can be taken to make sure VEP is running as fast as possible: 
https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster
 
 For example:
 For very large files (for example those from whole-genome sequencing), VEP process can be easily parallelised by dividing your file into chunks (e.g. by chromosome). 
 
 **3) Output file format:**
 
 VEP output formats are described at
 https://www.ensembl.org/info/docs/tools/vep/vep_formats.html
 
 Only 1 output format is available for a given run of VEP.
 
 Some options to convert VCF to tab are discussed in
 https://github.com/Ensembl/ensembl-vep/issues/346
 
 I hope that helps with the queries raised. 
 
 Regards
 Helen

**Comment by worker000000** [comment]
Thanks a lot for these helpful answers.

about selecting transcripts, I am talking about,
if I have 100 variants, annoting 100 genes, and I have a own defined classical transcripts for each gene, the command you mentioned seems to can only select one just like you said  function like grep.

# 
If you use --check_existing or any flags that invoke it (e.g. --af, --af_1kg, --filter_common, --everything), tabix-convert your cache file. Checking for known variants using a converted cache is >100% faster than using the default format.
# 
what does this means, does it suggest me to use any argument if I use arguments like  --af, --af_1kg

**Comment by aparton** [comment]
Hi @worker000000,

Thanks for your query. Regarding checking transcripts, then the filter VEP script can be used to select multiple transcripts. For example, the command `--filter "Feature is ENST00000307301,ENST00000307302,ENST00000307303" will allow you to select all transcripts that fall in your list of transcripts. Alternatively, you can use an input file like `--filter "Feature in /data/files/motifs_list.txt"`. 

Currently, the input command you sent to us has the `--pick` option included, which will be filtering your transcripts before providing output, and this filtering may exclude some of the transcripts that you are interested in. If you are interested in a particular set of transcripts that you have identifiers for, I suggest you remove the `--pick flag` and filter for these transcripts after your initial analyses with the filter VEP script.

Regarding optimising your VEP performance, if you have downloaded the VEP 104 cache using the perl installer then it will be tabix converted by default. However, VEP performance is highly dependant on the analysis you choose to run and the subsequent parameters used. Using `--af` is not particularly intensive and should not extend your VEP runtime significantly. However, the `--regulatory` flag requires significant additional resources and as such if you're looking to reduce your runtime then I would suggest not using this flag unless it is necessary.

If you have any further questions, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by worker000000** [comment]
Thanks a lot. I will remove --regulatory.
By saying --filter "Feature in /data/files/motifs_list.txt"`. 
I used the docker version of vep due to it is really hard to install the perl version.

https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html
this shows filter_vep seems to only accept the txt result of vep, does it support vep annotated vcf?

**Comment by aparton** [comment]
Hi @worker000000,

That's fine, the filter VEP script is also available through the docker installation. Additionally, filter VEP also works on VCF formatted VEP output.

Kind Regards,
Andrew

**Comment by helensch** [comment]
Hi @worker000000 

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen
