### ISSUE TITLE
Problem with cache file download

### ISSUE THREAD

**Issue by Panacotaforcota** [Ensembl/ensembl-vep#1024]
Hi! I'm having a problem with download of the cache files. I tried:

`curl -O http://ftp.ensembl.org/pub/release-104/variation/indexed_vep_cache/homo_sapiens_vep_104_GRCh38.tar.gz`

but after four hours I got:

`curl: (18) transfer closed with outstanding read data remaining`

**Comment by NavenM** [comment]
Hi,

I'm not sure whether this is a VEP specific issue so I probably can't offer much help, but there appear to be a few possible solutions [here](https://stackoverflow.com/questions/1759956/curl-error-18-transfer-closed-with-outstanding-read-data-remaining). If you're still struggling, then caches can be installed during VEP installation, as detailed in the [Tutorial](https://m.ensembl.org/info/docs/tools/vep/script/vep_tutorial.html).

If you continue to have issues with cache installation, just let me know.
Thanks

**Comment by kvn95ss** [comment]
Hello,

For some reason I could never fully download the cache files using ```curl``` or ```wget``` even with resume support. I would use jDownloader2 as it has very good resume support. It took me waay too much time to download the file, then again it could be due to my location (India) or the ISP (I was getting download speeds north of 200kbps)

**Comment by nakib103** [comment]
Hello, 

I am closing this as it is probably not a VEP related issue. This may happen as the files are large and because of network condition and settings.

There are some solutions to this particular error in the internet that might solve the problem in some cases (like keeping `--keepalive-time` timeout [low](https://stackoverflow.com/questions/33522615/curl-transfer-closed-with-outstanding-read-data-remaining)). 

Also there is option to download the cache as part of the [VEP installation](https://www.ensembl.org/info/docs/tools/vep/script/vep_tutorial.html).

If you face any further problems please let us know.

Best regards,
Nakib
