### ISSUE TITLE
add support for CADD and MutationTaster

### ISSUE THREAD

**Issue by asmlgkj** [Ensembl/ensembl-vep#1077]
## Describe the issue
thanks a lot for continous update of vep,  does vep support CADD and MutationTaster

**Comment by helensch** [comment]
Hi @asmlgkj 

CADD and MutationTaster are available via VEP Plugins.

For information on VEP Plugins see: 
https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html

MutationTaster is available via the dbNSFP VEP plugin.
For an example of use see the dbNSFP example on
https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html

The Ensembl Blog post also gives an overview
https://www.ensembl.info/2019/10/03/cool-stuff-the-ensembl-vep-can-do-predict-pathogenicity-of-missense-variants/

Regards
Helen

**Comment by asmlgkj** [comment]
Thanks a lot.
how can I used it in command , can you give an example?

**Comment by helensch** [comment]
Hi @asmlgkj 

For information on running VEP Plugins see 
https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html#plugins_use

Each VEP Plugin contains information on how to run and  any data needed.

There are links to the VEP Plugins from:
https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html

For CADD e104:
https://github.com/Ensembl/VEP_plugins/blob/release/104/CADD.pm

 `./vep -i variations.vcf --plugin CADD,/FULL_PATH_TO_CADD_FILE/whole_genome_SNVs.tsv.gz,/FULL_PATH_TO_CADD_FILE/InDels.tsv.gz`
 
For dbNSFP e104:
https://github.com/Ensembl/VEP_plugins/blob/release/104/dbNSFP.pm
```
 ./vep -i variations.vcf --plugin dbNSFP,/path/to/dbNSFP.gz,col1,col2
 ./vep -i variations.vcf --plugin dbNSFP,'consequence=ALL',/path/to/dbNSFP.gz,col1,col2
 ./vep -i variations.vcf --plugin dbNSFP,'consequence=3_prime_UTR_variant&intron_variant',/path/to/dbNSFP.gz,col1,col2
 ```
 
For an example of use see the dbNSFP example on
https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html

For example to include MutationTaster 
--plugin dbNSFP,/path/to/dbNSFP.gz,MutationTaster_score,MutationTaster_converted_rankscore,MutationTaster_pred 

Regards
Helen

**Comment by asmlgkj** [comment]
thanks a lot

how can I download file like  /FULL_PATH_TO_CADD_FILE/whole_genome_SNVs.tsv.gz,/FULL_PATH_TO_CADD_FILE/InDels.tsv.gz

**Comment by asmlgkj** [comment]
The exac seems to has a new version  release1 instead of currennt

**Comment by helensch** [comment]
Hi @asmlgkj 

From: https://github.com/Ensembl/VEP_plugins/blob/release/104/CADD.pm
" The plugin works with all versions of available CADD files. The plugin only
 reports scores and does not consider any additional annotations from a CADD
 file. It is therefore sufficient to use CADD files without the additional
 annotations. "
 
 The version will depend on your use case and assembly.
 
 The https://cadd.gs.washington.edu/download includes a recommendation on how to download the CADD files.
 
 I am not clear what you mean by "The exac seems to has a new version release1 instead of currennt", please can you provide further info.
 
 Regards
 Helen

**Comment by helensch** [comment]
Hi @asmlgkj 

The information for CADD download is at the top of the page 
https://cadd.gs.washington.edu/download
above
Developmental release: v1.6 [release notes]
From the page:
"Due to the large file sizes, we highly recommend a download manager or another tool that allows you to continue interrupted downloads (e.g. wget -c). Note that the latest versions also have a separate download option via the install script."

We recommend to users that they use gnomAD frequency data as built into our cache files, as an alternative to ExAC as described here: https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#gnomad

However, if you specifically require the older ExAC data for your analyses, please let me know.

Regards
Helen

**Comment by asmlgkj** [comment]
Thanks a lot.
I also see that.
I am asking file 


All possible SNVs of GRCh37/hg19 | US | DE (78G) | US | DE (2.6M)
All possible SNVs of GRCh37/hg19 incl. all annotations | US | DE (248G) | US | DE (2.6M)

<br>
which snv file is needed for  vep

**Comment by helensch** [comment]
Hi @asmlgkj 

As noted : https://github.com/Ensembl/VEP_plugins/blob/release/104/CADD.pm
" The plugin works with all versions of available CADD files. The plugin only
reports scores and does not consider any additional annotations from a CADD
file. It is therefore sufficient to use CADD files without the additional
annotations. "

So the file without the additional annotations can be used i.e. All possible SNVs of GRCh37/hg19 

The file with all the annotations is not needed ie. "All possible SNVs of GRCh37/hg19 incl. all annotations"  is not needed.

Regards
Helen

**Comment by asmlgkj** [comment]
Thanks a lot

**Comment by helensch** [comment]
Hi 

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards
Helen
