### ISSUE TITLE
VEP and HGVSp from VEP annotating same variant to 2 different amino acid positions

### ISSUE THREAD

**Issue by jon4thin** [Ensembl/ensembl-vep#1105]
When I compare the `Protein_position` column from VEP output to the amino acid position output by HGVSp in VEP, the position differs by 0-27 (~47k variants input). Interestingly, this seems to only occur with my frameshift variants (regardless of size).

I used the `--shift_hgvs 0` flag when running VEP, which I thought would mean that there would not be a difference. When I look at CDS_Postion vs HGVSc, there is no difference.

Why am I seeing this despite turning off the HGVS shift? Does `--shift_hgvs 0` only work for HGVSc? 

Here are some example SNPs:

chr15:75352332:T:TC
chr1:942886:G:GC
chr1:942151:GC:G 
chr1:23794342:AC:A
chr1:1625634:AC:A
chr1:15928646:GGA:G 

### System
- VEP version: 105
- VEP Cache version: 105

### Full VEP command line
```
vep -i ./vep_InputOutput/Input --dir_cache /data/software/condaVEP/homo_sapiens/105_GRCh38 --gff sorted.gencode.v39.basic.annotation.gff3.gz --fasta /data/resource/Homo_sapiens_assembly38.fasta ---no_stats --output_file ./vep_output/outputname --coding_only --hgvs --tab --shift_hgvs 0
```

**Comment by jamie-m-a** [comment]
Hi @jon4thin 

Apologies for the delay in responding, I'm just taking a look at this one and will get back to you.

**Comment by jon4thin** [comment]
Thank you for your effort, look forward to the response.

**Comment by jon4thin** [comment]
Any updates @jamie-m-a ?

**Comment by jamie-m-a** [comment]
Hi @jon4thin

I'm very sorry for the delay in getting back to you. I can replicate the issue you've reported and we are currently looking into the cause of it. I'll update on here when I have more information.

**Comment by jon4thin** [comment]
Just me pinging this conversation again :P 
@jamie-m-a

**Comment by jamie-m-a** [comment]
Hi @jon4thin 

Apologies again for the delay, but I believe I can explain the issue now.

So after looking into this further and consulting with the team, we believe that the shifting of HGVSp is appropriate behaviour due to the sequence context. So, for example:

15 75352332 75352332 T/TC

Reference seq: ATC_CCC_CCC_TTT -> Ile_Pro_Pro_Phe
With insertion:ATC_CCC_CCC_CTT -> Ile_Pro_Pro_Leu

-> a C is inserted after the T in the Ile at 188 but there is no change in the protein sequence until 3 peptides later (at pos 191).

In this case, it wouldn't be correct to say ENSP00000347170.4:p.188Ile here - we have to report where the change occurs, hence ENSP00000347170.4:p.Phe191LeufsTer2

For info, the HGVS recommendations are here:
http://varnomen.hgvs.org/recommendations/protein/variant/frameshift/

In contrast (and as you probably observed), the HGVSc position is affected by the switching on and off the of the --shift_hgvs option.

I hope this helps, please do ask if you any further questions or if this is not clear.

**Comment by jon4thin** [comment]
Oh wow yes, this makes perfect sense now. I am embarrassed I overlooked this.
And the Ter2 references 2 AA downstream of the first changed AA (Phe191) and not the site of the genetic variation (188). 

Thanks so much sorry about that.
