### ISSUE TITLE
Problem with dbNSFP plugin

### ISSUE THREAD

**Issue by dana-obk** [Ensembl/ensembl-vep#1127]
Hello,

I am running VEP using dbNSFP plugin like this:

```
perl ./vep -i my.vcf \
    --format vcf \
    --offline \
    --assembly GRCh37 \
    --sift b \
    --polyphen b \
    --symbol \
    --numbers \
    --biotype \
    --total_length \
    -o output \
    --vcf \
    -e \
    --plugin dbNSFP \
    --fasta hg19RCRS.fa
```

But I get an error:

```
Use of uninitialized value in pattern match (m//) at /home/user/.vep/Plugins/dbNSFP.pm line 159.
Use of uninitialized value $file in pattern match (m//) at /home/user/.vep/Plugins/dbNSFP.pm line 174.
Use of uninitialized value $file in pattern match (m//) at /home/user/.vep/Plugins/dbNSFP.pm line 176.
Use of uninitialized value $file in pattern match (m//) at /home/user/.vep/Plugins/dbNSFP.pm line 178.
Use of uninitialized value $file in pattern match (m//) at /home/user/.vep/Plugins/dbNSFP.pm line 180.
Use of uninitialized value $file in concatenation (.) or string at /home/user/.vep/Plugins/dbNSFP.pm line 183.
WARNING: Failed to instantiate plugin dbNSFP: ERROR: Could not retrieve dbNSFP version from filename

```

I tried to run `perl dbNSFP.pm` from plugin directory but I get the following error:

```
Can't locate Bio/EnsEMBL/Utils/Sequence.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at dbNSFP.pm line 142.
BEGIN failed--compilation aborted at dbNSFP.pm line 142.
```

When I try to download dbNSFP manually like this, I get an error as well. How to solve the problem with this plugin?

```
 wget ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFP4.1a.zip
--2022-03-10 09:32:58--  ftp://dbnsfp:*password*@dbnsfp.softgenetics.com/dbNSFP4.1a.zip
Resolving proxy (proxy)... 172.23.1.77
Connecting to proxy (proxy)|172.23.1.77|:8080... connected.
Proxy request sent, awaiting response... 404 Not Found

```

**Comment by nakib103** [comment]
Hello @dana-obk ,

Thanks for your question.

To run the plugin you need to at least provide the path of the dbNSFP file and the columns from the dbNSFP file that you want in the output. There is example in the [plugin ](https://github.com/Ensembl/VEP_plugins/blob/release/105/dbNSFP.pm) SYNOPSIS - 

```
 ./vep -i variations.vcf --plugin dbNSFP,/path/to/dbNSFP.gz,col1,col2
```

You can use "ALL" instead of specifying individual column names which will you give you all the columns in the output file. 

So, first you need to download the dbNSFP file. I can see that  you are facing issue for that. Looking at the FTP site it seems that 4.1a version is missing there currently. You can try downloading other version (4.2a, 4.3a etc.) from FTP. The url will be same just change the version part (e,g - ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFP4.2a.zip). 

Or, if you like, [here](https://sites.google.com/site/jpopgen/dbNSFP) you will find google drive link for download. For 4.1a it should be - https://drive.google.com/file/d/17kdX1Fqi_ZW8PXaHm2vQuJLHuoMDwZmB/view?usp=sharing 

Remember to process the file after downloading as mentioned in the plugin description - 

```
 > unzip dbNSFP4.1a.zip
 > zcat dbNSFP4.1a_variant.chr1.gz | head -n1 > h
 > zgrep -h -v ^#chr dbNSFP4.1a_variant.chr* | awk '$8 != "." ' | sort -T /path/to/tmp_folder -k8,8 -k9,9n - | cat h - | bgzip -c > dbNSFP4.1a_grch37.gz
 > tabix -s 8 -b 9 -e 9 dbNSFP4.1a_grch37.gz
```

Best regards,
Nakib

**Comment by dana-obk** [comment]
thanks a lot Nakib, I will now try to follow your suggestions and will update. The download of 4.2a version is really slow, I was wondering if this is normal?

**Comment by nakib103** [comment]
Great, let me know if you face any issue.

The download of course depends on the internet speed. And, the file size is ~34GB - so it can take a while to download.

**Comment by nakib103** [comment]
Hello @dana-obk , 

It is unfortunate that your download is failing. There can be number of cause why that might happen. I can suggest you the following - 

1. if you were using wget command; you can just use the same command again with the -c flag and it will resume download from where it stopped. 
2. you can try downloading from their google drive link. The links can be accessed from this page - https://sites.google.com/site/jpopgen/dbNSFP

**Comment by dana-obk** [comment]
Thanks for your reply.
I was downloading with -c option, but the connection does not seem to be stable as it breaks and closes. 
Anyway, I followed your option 2 and finally managed to download it to my local PC in few hours!!! thanks a lot!

**Comment by nakib103** [comment]
I am closing this issue as the problem seems to be resolved. Please feel free to open an issue again if you face any further problems.

Kind regards,
Nakib
