### ISSUE TITLE
Variant Recoder batch request (1million queries)

### ISSUE THREAD

**Issue by charwang0440** [Ensembl/ensembl-vep#1172]
Hi,
I am trying to use variant recorder to convert HGVS to RefSeq format (all NPs and alternative isoforms-hgvsp) but I have around 1 million queries. The online tool only supports 20MB of input files and fails after running it for two days. The API and command-line tools are slow and take a long time to process all the queries. The API connection time is also limited, as 1000 queries often disconnect with the server. 
Are there other ways you can suggest to use these tools for large data queries in an efficient manner, or any local instantiations?

**Comment by jamie-m-a** [comment]
Hi @charwang0440 

I'm sorry to hear about the difficulties you've been having with running your queries on variant recoder.

Unfortunately, at present we do require the database connection for this tool to run and as you have noted it may fail when processing large numbers of variants.

As a potential quick fix, I would suggest perhaps splitting your input in to smaller chunks, in order to minimise the impact of a failure. There are some tweaks we are looking to make to the code that should improve the processing of large numbers of variants, but those changes are likely to be several months away.

We have considered creating an offline version of the variant recoder tool, but it's a relatively low priority task at present and I can't confirm that we would definitely doing it.

I can keep this ticket open if you like, so we can update you as improvements are made to the running of variant recorder, but as I mentioned above, this is not likely to be int he near future.

**Comment by jamie-m-a** [comment]
As I haven't received any follow up on this issue I'm going to close it off. But please feel free to reopen it if you want any further information.
