### ISSUE TITLE
VEP is not outputting HGVSp predictions for certain variants

### ISSUE THREAD

**Issue by rached-97** [Ensembl/ensembl-vep#1179]
## Describe the issue
For certain variants, VEP is able to predict their effect on CDS, but does not output an HGVSp prediction. For example:
```
                                                                                                 vcf_variant            Gene  SYMBOL         Feature                             Consequence HGVSp
1: chr10:87961028:CAAGGAATATCTAGTACTTACTTTAACAAAAAATGATCTTGACAAAGCAAATAAAGACAAAGCCAACCGATACTTTTCTCCAAATTTT>C ENSG00000171862    PTEN ENST00000371953                        inframe_deletion  <NA>
2:                                                                                    chr11:125629457:AGGG>A ENSG00000149554   CHEK1 ENST00000428830  inframe_deletion,splice_region_variant  <NA>
3:                                                                chr15:90467590:C>CAGGTAGGTTACCTTTCTTCACGAA ENSG00000140575  IQGAP1 ENST00000268182 inframe_insertion,splice_region_variant  <NA>
4:                         chr19:42287663:TGGGCGAGTGGTGGTATGCCCTGGGGCCCAAGGAGAAGCAGAAGTACCACGACCTGGCCTTCCA>T ENSG00000079432     CIC ENST00000575354  inframe_deletion,splice_region_variant  <NA>
5:                                                                               chr8:119106188:G>GGCAACAAAA ENSG00000184374 COLEC10 ENST00000332843                       inframe_insertion  <NA>
```
### Full VEP command line
I used the web interface of VEP on this date with the following VCF input
```
10 87961028 . CAAGGAATATCTAGTACTTACTTTAACAAAAAATGATCTTGACAAAGCAAATAAAGACAAAGCCAACCGATACTTTTCTCCAAATTTT C . . .
11 125629457 . AGGG A . . .
15 90467590 . C CAGGTAGGTTACCTTTCTTCACGAA . . .
19 42287663 . TGGGCGAGTGGTGGTATGCCCTGGGGCCCAAGGAGAAGCAGAAGTACCACGACCTGGCCTTCCA T . . .
8 119106188 . G GGCAACAAAA . . .
```

**Comment by diegomscoelho** [comment]
Hi @rached-97,

Our feature in `VEP` will not annotate HGVSp which variants falls into intronic regions. Besides that, VEP reports the consequences exactly in the position of the duplication but this change should be described at the 3' most position. After release 100, we introduced new flags so that VEP can optionally convert variant alleles to their most 3’ representation before consequence calculation. If you use:
`Right align variants prior to consequence calculation:` = `Right align relative to transcript`

![image](https://user-images.githubusercontent.com/10541523/168572468-cbd80782-c0f3-49a2-833a-9257714bca11.png)

You will see that even exonic inframe alterations will fall into intronic regions, after using this option.

We are still investigating why `8:119106188-119106188` wasn't properly annotated. Any news I will keep you updated here.

Regards, @diegomscoelho

**Comment by xiucz** [comment]
@diegomscoelho 
Which command option does the `Right align variants prior to consequence calculation: = Right align relative to transcript` refer to?
Thank you,
xiucz

**Comment by diegomscoelho** [comment]
Hi @xiucz,

It's same as execute vep with option: `--shift_3prime 1`.

Best, Diego

**Comment by diegomscoelho** [comment]
Hi @rached-97,

I am going to close this issue now.

If you have any further questions, please feel free to reopen it or create a new issue.

Regards,
@diegomscoelho
