### ISSUE TITLE
VEP --mirna annotates more than miRNAs

### ISSUE THREAD

**Issue by ntm** [Ensembl/ensembl-vep#1278]
## Describe the issue
Hello VEP devs,
I am trying out the --mirna option to VEP, which according to the doc "Reports where the variant lies in the miRNA secondary structure". This sounds interesting, but I would expect it to only annotate variants hitting microRNAs (BIOTYPE==miRNA). However in my tests I get annotations in the "miRNA" field for a variety of BIOTYPEs including snoRNA and snRNA.
For example, running VEP --miRNA on rs150964208 , I obtain an annotation for the snoRNA SNORA15 that contains "miRNA_loop" in the miRNA field. This seems wrong?

### System
- VEP version: 107
- VEP Cache version: homo_sapiens_vep_107_GRCh38
- Perl version: perl-5.16.3-299.el7_9.x86_64
- OS: CentOS 7
- tabix installed ? yes

### Full VEP command line
The result is obtained using the VEP web interface, checking the "miRNA structure" box.

### Full error message
None, but the result is unexpected.

**Comment by ntm** [comment]
Hi @nuno-agostinho,
If this is due to mislabelling of snoRNA15 , the problem isn't isolated to this gene: I am seeing a similar behaviour with other ncRNAs that aren't miRNAs. Here are some examples that could be useful:
rs587636794 hitting RNVU1-17 (snRNA)
rs193148354 hitting RN7SKP95 (misc_RNA)
rs184418279 hitting RN7SKP189 (misc_RNA)
Thanks for looking into this.
Nicolas

**Comment by nuno-agostinho** [comment]
Hey @ntm, just opened PR #1280 that ensures that `--miRNA` only reports structures in ncRNAs with biotype `miRNA`, instead of any ncRNA with structural data. This fix should be available in release 109.

However, this does make me wonder if VEP should show structures for other ncRNAs as well... 🤔

Anyway, sorry for the issue. I'll close this issue after the code has been merged and if you don't have any other question for me. Thanks for reporting!

Cheers,
Nuno

**Comment by nuno-agostinho** [comment]
Hey @ntm,

The fix is now merged and is going to be available in release 109, thanks for your help!

Thanks,
Nuno
