### ISSUE TITLE
HGVS_OFFSET missing

### ISSUE THREAD

**Issue by andrew2k** [Ensembl/ensembl-vep#1328]
## Describe the issue
I runned VEP on a vcf file generated by the GATK pipeline. 
Vep changes of 1 nucleotide the coordinates of several input mutations. 
Besides, it doesn't report HGVS_OFFSET.

### System
- VEP version: 108.2
- VEP Cache version: 108_GRCh37
- OS: linux
- tabix installed

### Full VEP command line
```
vep --cache --format vcf --af_gnomad --hgvs --port 3337 --fasta genome_hg19.fa --hgvsg --symbol \
	--dir vep_dir --species ${species} -i inputFile -o outputId_vep_annotations.vcf
```

### Example Input ###
chr6	111983041	.	CT	C	.	PASS	AS_FilterStatus=SITE;AS_SB_TABLE=867,733|15,14;DP=1711;ECNT=1;GERMQ=93;MBQ=20,20;MFRL=196,185;MMQ=60,60;MPOS=39;POPAF=7.30;RPA=5,4;RU=T;STR;STRQ=93;TLOD=10.25	GT:AD:AF:DP:F1R2:F2R1:SB	0/1:1600,29:0.016:1629:820,10:764,19:867,733,15,14

### Example Output ###
chr6_111983042_T/-	chr6:111983042	-	ENSG00000010810	ENST00000229470	Transcript	frameshift_variant	1937	1358	453	K/X	aAg/ag	COSV57612665,COSV57616025	IMPACT=HIGH;STRAND=-1;SYMBOL=FYN;SYMBOL_SOURCE=HGNC;HGNC_ID=4037;HGVSc=ENST00000229470.5:c.1358del;HGVSp=ENSP00000229470.5:p.Lys453ArgfsTer53;HGVSg=chr6:g.111983046del;SOMATIC=1,1;PHENO=1,1

Thx a lot,
Best

**Comment by andrew2k** [comment]
I tried now to add the --shift_hgvs 0 parameter.
The output doesn't change. It seems that it does not consider that parameter.

**Comment by andrew2k** [comment]
Hi Diego,

I tried to add the flag --assembly GRCh37 but the results don't change.
I still get 1 nucleotide mismatch in the coordinates (i.e. 111983042 instead of 111983041 ).

I try to attach you the raw input file.
[19W169_S4_somatic_m2_filtered_pass.vcf.gz](https://github.com/Ensembl/ensembl-vep/files/10247727/19W169_S4_somatic_m2_filtered_pass.vcf.gz)

Let me know if this helps.

Thx, regards,
Andrea

**Comment by diegomscoelho** [comment]
Hi @andrew2k,

VEP default output have a different behavior than `VCF` in your output:
`chr6_111983042_T/-` is indicating that T has been removed (from position 111983042).
That would be the same as: `chr6 111983041 . CT C . . .` (your VCF input)
That's why it appears `111983042` instead of `111983041`

About `HGVS_OFFSET`, it was decided to not include in output if it is equals to 0 (zero) due to output size. Thanks for highlighting this to us, we will include this behavior in our website to make it clear for future users.

Best, @diegomscoelho

**Comment by diegomscoelho** [comment]
Hi @andrew2k,

More information about `HGVS_OFFSET` was included in release 109 docs. Thanks for reporting your problem. I will close this issue now, any question feel free to post it here.

Best, @diegomscoelho
