### ISSUE TITLE
Wrong HGVSc

### ISSUE THREAD

**Issue by Akazhiel** [Ensembl/ensembl-vep#1342]
## Describe the issue
The output for the HGVSc notation of some variants is wrong.

## Additional information
When annotating this variant `1-236702294-GA-G` I get the following HGVSc `ENST00000434231.2:c.*4del` but this is wrong because this variant is a deletion of the last nucleotide in the stop codon of the transcript, meaning the HGVSc returned should be `ENST00000434231.2:c.162del`. This tends to happen with variants that cause a stop_lost, because for some reason I believe the annotation is shifting the genomic position 4 bases downstream, the same way if I annotate this same variant, for a different transcript I get the following HGVSc `ENST00000238181.7:c.255del` but then the CDS position that appears in the annotation is 251, how is all this possible?

### System
- VEP version: 104
- VEP Cache version: 75
- Perl version: [e.g. 5.26]
- OS: Ubuntu
- tabix installed 

Thanks,

Jonatan

**Comment by likhitha-surapaneni** [comment]
Hi @Akazhiel ,

We are following the guidelines whereby the most 3’ position possible of the reference sequence is arbitrarily assigned to have been changed, as described here: http://varnomen.hgvs.org/recommendations/general/


<img width="722" alt="Screenshot 2023-02-10 at 06 51 09" src="https://user-images.githubusercontent.com/10923198/218059908-b76a9f07-ef7f-484b-b925-9e5fdc6e3726.png">

According to the HGVS 3' rule, the variant must be described at the most 3' position which takes it outside the coding region of  ENST00000434231.2, which is here labelled LGALS8-028.

Due to the 3' rule, the CDS position of the variant for ENST00000238181.7 (labelled as LGALS8-011) is reported as 255. 

Hope this answers your question!

Kind regards,
Likhitha
