### ISSUE TITLE
Recompute stats

### ISSUE THREAD

**Issue by vilperte** [Ensembl/ensembl-vep#1363]
Hello,

I was wondering if there is a way to recreate the stats.html after filtering an already annotated vcf? I've searched in the documentation and it doesn't seem possible. That would be a very useful feature.

Thank you

**Comment by nuno-agostinho** [comment]
Hey @vilperte, hope you are having a great day!

I am not sure if I understand what exactly is your suggestion, but I think it is either:

1. Assuming that you filter with `filter_vep`, `filter_vep` should output a `stats.html` for filtered variants.
2. Be able to create the `stats.html` from any VCF regardless of the filtering command used.

We have a previous request to do the first point, but please expand a bit on your suggestion. Thanks!

Kind regards,
Nuno

**Comment by vilperte** [comment]
Thanks for the quick reply.

My idea was more on point two, because we mainly filter existing vcfs using bcftools for AF or other INFO field. But I could also see an use for the first point. Either possibilities would be great.

Cheers,

Vinicius

**Comment by nuno-agostinho** [comment]
Hey @vilperte,

Extending `filter_vep` sounds easier to do, but I will discuss with the team to see what they think about allowing to get stats for any VCF file.

Thanks for your suggestion!

Best,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @vilperte,

Hope you are having a nice day.

Currently, the statistics generated during VEP execution rely on internal data. Re-calculating these statistics would require developing new code, which is not a priority for us at the moment.

However, we do plan to keep this in mind for future improvements. Since it's a lower priority right now, I will close this ticket. I am sorry for the inconvenience.

Best regards,
Nuno
