### ISSUE TITLE
I need specific output from vep

### ISSUE THREAD

**Issue by bioinfo2016** [Ensembl/ensembl-vep#1377]
I run vep on vcf file of human sample. I need the have following output in output file:
1) ReadDepth > 60
2) VariantQual == PASS
3) VEP_VAR_IMPACT == HIGH or MODERATE
4) CANNONICAL_TRAS == Y
5) 5.1) CCDS_ID and
5.2)RefSeqTransID and
5.3) EnsemblTransID == not NULL
6 ) 6.1) SwissVar == Disease
6.2) ClinVar_Des == PATHOGENIC
6.3) HGMD_VarClass == DiseaseCausingPathological

My question what are the options that  show me these output.?
### System
- OS:  Ubuntu
- tabix: installed

### Full VEP command line
```
./vep -i  input.vcf -o output.vcf --plugin home/u1/.vep/Plugins --offline --use_given_ref --force_overwrite --cache --dir_cache /home/u1/.vep
```
Thanks in advance for your help.

**Comment by likhitha-surapaneni** [comment]
Hi @bioinfo2016 , thank you for approaching us!

VEP currently supports the following [options](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html) 

In order to filter an existing VCF file, [vep_filter](https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html) provides documentation to filter data based on certain criteria. Furthermore, [bcftools +split-vep ]( https://samtools.github.io/bcftools/howtos/plugin.split-vep.html )can be used to modify the output file in a certain way. 

Hope the information provided is useful. Please let us know if you have any more questions.

Kind regards,
Likhitha

**Comment by bioinfo2016** [comment]
Thanks @likhitha-surapaneni for your reply. But I still do not know what are the proper filters that show the above information in the output file.

Regards
Badr

**Comment by likhitha-surapaneni** [comment]
Hi @bioinfo2016 ,

The following are some examples for [filter_vep](https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html) :

`./filter_vep -i out.txt -o out_filtered.txt --filter "IMPACT is HIGH or IMPACT is MODERATE"` to filter out variants with impact HIGH or MODERATE

`./filter_vep -i out.txt -o out_filtered.txt --filter "CANONICAL is YES"` to filter canonical transcripts. Please note that `filter_vep` works for fields present in the VEP results file. In order to indicate if the transcript is the canonical transcript for the gene, [--canonical](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_canonical) option can be used while running VEP

The above filter conditions can also be combined in the following way:
`./filter_vep -i out.txt -o out_filtered.txt --filter "IMPACT is HIGH or IMPACT is MODERATE and CANONICAL is YES"` 

I hope the above examples describe the usage of `filter_vep` and how the fields from the VEP results file can be used in the filter conditions

Kind regards,
Likhitha
