### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by parlar** [Ensembl/ensembl-vep#14]
Hi,

Thanks for the good work you're doing! I tried the vep.pl beta and noticed some irregularities. 

1:
When multiple accessions are present under the TREMBL field, they are separated using commas (,). This is not optimal for parsing since the whole annotation lines (in case multiple transcripts exist) are also separated using commas. For Existing_variation, the separator is "&", which is much better.

2:
It did not seem to fork runs to multiple threads?

**Comment by willmclaren** [comment]
Thanks for the spot.

1 is fixed by https://github.com/Ensembl/ensembl-vep/commit/8007e1631c541d9e2f89bf67c11b0b3df20a96e2 ; only on master at the moment as it changes JSON output as used by our REST server, prefer not to change this mid-release.

2 Forking works in a similar manner to the previous version, just use `--fork [num_forks]` . It is somewhat different to a traditional multi-threaded processing model.

**Comment by parlar** [comment]
Thanks. I only saw one instance running instead of multiple. And I did not see > 100% of cpu usage either. But maybe I missed something..

**Comment by kmhernan** [comment]
@willmclaren just letting you know what I saw the usage of `,` delimiter instead of `&` delimiter in `RefSeq` column and in plugin outputs; not sure if that was part of your fix

**Comment by willmclaren** [comment]
@kmhernan this should be fixed now by https://github.com/Ensembl/ensembl-vep/commit/0faefefa5f5e35b62ad37ea2d0fea40f53b80e75
