### ISSUE TITLE
HGVS & refseq

### ISSUE THREAD

**Issue by equinne5** [Ensembl/ensembl-vep#1415]
Hi, Id like to generate HGVS notations that use RefSeq transcripts as the reference sequence & this works fine by adding --refseq  however I notice that when I do this the --mane_select is changed to an Ensembl transcript ID -whereas when I run it without --refseq its the refseq transcript ID. 

e.g.  
`vep --cache --offline --format vcf --vcf --force_overwrite --i {vcf} -o {annotated.vcf}  --mane  --fork 10 --symbol --pick --max_af  --exclude_null_alleles --check_existing --af_gnomadg --af_gnomade --fasta /opt/vep/.vep/homo_sapiens/109_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --hgvs --refseq `

returns 
Chromosome	Pos	REF	ALT	HGVSc	HGVSp	MANE_SELECT
chr22	16591593	A	G	NM_014406.5:c.958T>C	NP_055221.1:p.Trp320Arg	ENST00000359963.4

whereas 
`vep --cache --offline --format vcf --vcf --force_overwrite --i {vcf} -o {annotated.vcf}  --mane  --fork 10 --symbol --pick --max_af  --exclude_null_alleles --check_existing --af_gnomadg --af_gnomade --fasta /opt/vep/.vep/homo_sapiens/109_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --hgvs`

returns 
Chromosome	Pos	REF	ALT	HGVSc	HGVSp	MANE_SELECT
chr22	16591593	A	G	ENST00000359963.4:c.958T>C	ENSP00000353048.3:p.Trp320Arg	NM_014406.5

Im using docker and ensembl-vep   : 109.3

Just wondering if Im doing something wrong or if there's any way around this? 

thanks!

**Comment by likhitha-surapaneni** [comment]
Hi @equinne5 , we are able to replicate this on our end. We are trying to investigate this further.

**Comment by likhitha-surapaneni** [comment]
Hi @equinne5 , thank you for your patience. This is the expected behaviour. `--mane` returns the accession for a matching transcript. If the feature is a RefSeq transcript, the MANE column gives the matching Ensembl identifier and if the feature is an Ensembl transcript, the MANE column gives the matching RefSeq identifier. We will improve the docs from our side to make this clearer. Please feel free to open a new ticket if there are any further issues.

Kind regards,
Likhitha
