### ISSUE TITLE
vep installations every time? 

### ISSUE THREAD

**Issue by sruthisrini** [Ensembl/ensembl-vep#1564]
Hello,

I am using VEP to annotate my files. However, each time I attempt to use VEP, I find myself having to reinstall all the prerequisites, such as MySQL, Homebrew, and so on.

For instance, I install all the prerequisites and use VEP today. However, when I try to use it two days later, I encounter the following error:

`install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module)`

When I checked:
mysql --version
`mysql  Ver 8.0.34 for macos13.3 on x86_64 (Homebrew)
`

Is there a way to avoid reinstalling these dependencies every time I use VEP? The repetitive installations sometimes lead to issues due to version upgrades or other factors. Could you please provide a possible solution to run VEP using a simple input command without the need for reinstallations each time?

Thanks in advance.

Best,
Sruthi

**Comment by nuno-agostinho** [comment]
Hello @sruthisrini,

The situation that you report about requiring to constantly install the dependencies to use VEP is not expected behaviour and I do not understand why that is happening. Could you show an example of the command that you usually use to run VEP?

> install_driver(mysql) failed: Can't locate DBD/mysql.pm in @INC (you may need to install the DBD::mysql module)

The error message is complaining that `DBD/mysql.pm` (the Perl package) is not available in your system (this is not related with the `mysql` command). Can you retry installing DBD::mysql? Note that you will need to install version 4.050 as newer versions deprecated support for MySQL 5 (which our databases are still using).

If you are having issues with dependencies, you can also try using our official Docker image that allows to directly use VEP without installing its dependencies: https://hub.docker.com/r/ensemblorg/ensembl-vep

Best regards,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @sruthisrini, do you have any updates on this issue? Thanks and hope you are having a great day!

**Comment by nuno-agostinho** [comment]
Hi @sruthisrini,

I will close this ticket now since we haven't heard back from you. Feel free to open a new ticket if you are still facing issues.

Thanks,
Nuno
