### ISSUE TITLE
problems of haplo results

### ISSUE THREAD

**Issue by dosshra** [Ensembl/ensembl-vep#1577]
Hello,
I am not sure if it is a bug, a problem with my input, or my misunderstanding of the output of haplo.
## Describe the issue

I run   haplo and vep locally with the same input files (vcf,refernce -fasta, gff)
I get the following haplotype in haplo output:

> TRIDC4Bv3G05190000.1    TRIDC4Bv3G05190000.1:190G>C,398C>G,605C>T,1127C>T          TRIDC4Bv3G05190000.1.p:64G>R,131del{338}        indel 

looking for the variants in the vep output I get: 

> Chr4B_15122250_G/A      Chr4B:15122250  A       TRIDC4Bv3G05190000      TRIDC4Bv3G05190000.1    Transcript      missense_variant        1127    1127    376     T/I     aCc/aTc -       IMPACT=MODERATE;STRAND=-1;SOURCE=QTL4B_WEW_ZV_V2_adj.srt.gff.gz
Chr4B_15123397_G/A      Chr4B:15123397  A       TRIDC4Bv3G05190000      TRIDC4Bv3G05190000.1    Transcript      missense_variant        605     605     202     S/L     tCa/tTa -       IMPACT=MODERATE;STRAND=-1;SOURCE=QTL4B_WEW_ZV_V2_adj.srt.gff.gz
Chr4B_15123604_G/C      Chr4B:15123604  C       TRIDC4Bv3G05190000      TRIDC4Bv3G05190000.1    Transcript      missense_variant        398     398     133     A/G     gCc/gGc -       IMPACT=MODERATE;STRAND=-1;SOURCE=QTL4B_WEW_ZV_V2_adj.srt.gff.gz
Chr4B_15124847_C/G      Chr4B:15124847  G       TRIDC4Bv3G05190000      TRIDC4Bv3G05190000.1    Transcript      missense_variant        190     190     64      G/R     Ggc/Cgc -       IMPACT=MODERATE;STRAND=-1;SOURCE=QTL4B_WEW_ZV_V2_adj.srt.gff.gz

I wonder why do I see the deletion in the protein haplotype when in the DNA haplotype and in the vep output there is no indication of deletion or stop change. This is just one example, I saw several haplotypes like this.  Thank you

### System
- VEP version: 110 
- VEP Cache version: NA
- Perl version: 5.34.0
- OS:  Ubuntu 
- tabix installed globally by cpan , not in vep directory, installed 23/12/2023

### Full VEP command line
```
./haplo -i dom_vs_wt_snp_4Bqtl_sort.vcf -fasta  zavitan_nano_4B_510MB.fas -gff QTL4B_WEW_ZV_V2_adj.gff.gz -o haplo_vep_4b_QTL_2
```
vep is run with the same arguments.  See attached input files:
[haplo_vep.tr.gz](https://github.com/Ensembl/ensembl-vep/files/13776527/haplo_vep.tr.gz)

**Comment by nakib103** [comment]
Hello, @dosshra,

Thanks for your query!

Even if there is no indels in VEP result Haplosaurus can give deletion. This fundamental difference comes because VEP treat each input variant differently whereas Haplosaurus tries to generate a haplotype using multiple variants overlapping a transcript. A good example is -

```
# Input
#CHROM  POS   ID           REF     ALT QUAL  FILTER  INFO  FORMAT  IND1  IND2
12  6029429   rs1800380    C       T   .     .       .     GT      1|0   1|0
12  6029431   rs370984712  G       A   .     .       .     GT      1|0   1|0

# Output
ENST00000261405 | ENST00000261405:2878C>T,2880G>A | | ENSP00000261405:960R>*,961del{1854} | stop_change | | rs370984712,rs1800380 | IND1:1,IND2:1
```

The first variant is missense (**C**GG/**T**GG) and second is synonymous (CG**G**/CG**A**) but when forming haplotype with both it introduced a stop gain (**C**G**G**/**T**G**A**). You can find more information on Haplosaurus [here](https://www.ensembl.org/info/docs/tools/vep/haplo/index.html).

From your example of VEP output I do not see any indication of deletion too. But from the input that you provided I can see there are more variants between the variants you provided as VEP output. I wonder why they are not in the output. Unfortunately, as you are using custom fasta and gff it is not possible for me re-produce the issue. Did you see any other errors when running VEP/Haplosaurus?

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @dosshra,

I will close this issue for now. But if you face any further problems feel free to open a new one.

Best regards,
Nakib
