### ISSUE TITLE
Some plugins names have been possibly misspelled

### ISSUE THREAD

**Issue by stefanucci-luca** [Ensembl/ensembl-vep#1596]
## Describe the issue

When working with the latest singularity container plugins, PrimateAI, maveDB, and variety have been misspelled (upper or lowercase) and, therefore, can't be found. 

Install the modules:
singularity exec -B .cache_VEP/vep_data/:/opt/vep/.vep /software/teamtrynka/singularity/vep.sif INSTALL.pl -a p -c /opt/vep/.vep -g MaveDB,PrimateAI,VARITY,

command run:
```
singularity exec -B .cache_VEP/vep_data/:/opt/vep/.vep /software/singularity/vep.sif \
  vep --cache --offline --species homo_sapiens \
  --assembly GRCh38 --dir_cache /opt/vep/.vep --tab \
  --everything -i /container/test_vep.tsc \
  -o /container/test_out_vep \
  --plugin PrimateAI,/plugin_resources/primateAI/PrimateAI_scores_v0.2_GRCh38_sorted.tsv.bgz
```

warning message returned:
```
WARNING: Failed to compile plugin PrimateAI: Can't locate PrimateAI.pm in @INC (you may need to install the PrimateAI module) (@INC contains: /opt/vep/.vep/plugins /opt/vep/src/ensembl-vep/modules /opt/vep/src/ensembl-vep /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at (eval 53) line 2.
BEGIN failed--compilation aborted at (eval 53) line 2.
```

**Comment by likhitha-surapaneni** [comment]
Hi @stefanucci-luca ,

The plugins and their dependencies are pre-installed in the docker/singularity images ([docs](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker)). The error may have occurred due to the reinstallation of plugins `-a p -c /opt/vep/.vep -g MaveDB,PrimateAI,VARITY`. The latest instructions to download cache for the singularity image are available [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#singularity). Hope this helps.

Kind regards,
Likhitha

**Comment by likhitha-surapaneni** [comment]
Hi @stefanucci-luca , I hope the problem got resolved. I am closing this issue for now, please feel free to open a new issue if there are any further problems.
