### ISSUE TITLE
filter_vep not correctly filtering CADD_PHRED scores

### ISSUE THREAD

**Issue by kevin198930** [Ensembl/ensembl-vep#1610]
Hello,

I am trying to filter a .txt file that was generated from my vcf after running vep with the CADD plugin. I want to keep only the variants with a CADD_PHRED score > 20, however when I run the following bash script, I still see variants left with CADD_PHRED scores less than 20. I thought maybe the filtering worked in the inverse method and changed the --filter to CADD_PHRED score < 20, but I am still seeing variants in the output file with scores both less than 20 and more than 20. The CADD_PHRED scores are located in the "Extra" column of the txt file. I've included the original command used below:

 #!/bin/bash
for f in *_variant_effect_output_CADD_update.txt # for each sample
do
n=${f%%_variant_effect_output_CADD_update.txt} # strip part of file name
filter_vep --format tab -i ${n}_variant_effect_output_CADD_update.txt --filter "CADD_PHRED > 20" -o ${n}_variant_effect_output_CADD_filtered.txt
done

I've include the vep versions below:

Versions:
  ensembl              : 111.a6cc543
  ensembl-funcgen      : 111.5327cdd
  ensembl-io           : 111.dbba8d6
  ensembl-variation    : 111.d616b1e
  ensembl-vep          : 111.0

Thanks

**Comment by jamie-m-a** [comment]
Hi @kevin198930 

Could you give an example of some variants you haven't been able to filter correctly?

filter_vep is intended for use on the vep output format or VCF, it may be that your .txt is not suitable for it to work correctly.

**Comment by kevin198930** [comment]
Sure, I can attach the vep output .txt file. I had to delete many of the variants as the file was too large to upload. You can see there are variants with CADD_PHRED scores both less than and more than 20. I would like to keep only those variants with a score > 20. 
[s1_variant_effect_output_CADD_update.txt](https://github.com/Ensembl/ensembl-vep/files/14285313/s1_variant_effect_output_CADD_update.txt)

**Comment by jamie-m-a** [comment]
Hi @kevin198930 

Sorry for the delay in responding and thank you for uploading an example of the data, I can see the problem now.
Your output file has some extra characters that are preventing filter_vep from working correctly.

Firstly there seem to be some rogue `"` in there, secondly, the new line character is the DOS `\r\n` rather than `\n`

To clean these out I ran the following in linux:
`sed -e 's/"//g ; s/\r//g' s1_variant_effect_output_CADD_update.txt > cleaned.txt`

And filter_vep now works correctly on the cleaned output.

**Comment by kevin198930** [comment]
Hi Jamie,

Thank you for your help with this. Unfortunately, I am still seeing variants remaining after filtering that have CADD_PHRED scores both less than 20 and more than 20. I first used the sed command that you shared and then ran the same bash script I shared above on the cleaned.txt file.

**Comment by jamie-m-a** [comment]
Hi @kevin198930 

Sorry I forgot to mention, you don't need` --format tab,` that's for when the information in the extra section of the file is separated by tabs rather than the default semicolon. Try running without it and it should work.

**Comment by kevin198930** [comment]
Hi Jamie,

Sorry, again no luck. I removed the --format tab flag and I'm still seeing variants remaining after filtering that have CADD_PHRED scores both less than 20 and more than 20.

**Comment by jamie-m-a** [comment]
Hi @kevin198930 

I cannot replicate your issue once the variant file has been cleaned. What I can suggest is that perhaps your bash script  introduces double quotes (") into the variant output file, or perhaps these come from somewhere earlier in your process. But these may cause the INFO section to be evaluated as a string rather than looking at the numerical values within the fields. Which unsurprisingly breaks anything trying to filter numerically.

As I say though, when I downloaded your data, and removed the extraneous characters (which are not part of the standard VEP output), I am able to use filter_vep to correctly show only those variants with a CADD_PHRED > 20.

I suggest either a) use the sed command after running your bash script or b) seeing if you can identify where the extra characters are getting added to the variant files and fix it.

**Comment by kevin198930** [comment]
Hi Jamie,

I appreciate your help, I have attached the cleaned variant file to see if maybe it is not fully cleaned of these extra characters. I'm not sure if something went wrong generating this file. I used the following bash script to clean the extra characters:

#!/bin/bash
for f in *_variant_effect_output_CADD_update.txt # for each sample
do
n=${f%%_variant_effect_output_CADD_update.txt} # strip part of file name
sed -e 's/"//g ; s/\r//g' ${n}_variant_effect_output_CADD_update.txt > ${n}_variant_effect_output_CADD_update_cleaned.txt
done

I then used the following script to filter the CADD_PHRED scores on the cleaned file:

#!/bin/bash
for f in *_variant_effect_output_CADD_update_cleaned.txt # for each sample
do
n=${f%%_variant_effect_output_CADD_update_cleaned.txt} # strip part of file name
filter_vep -i ${n}_variant_effect_output_CADD_update_cleaned.txt --filter "CADD_PHRED > 20" -o ${n}_variant_effect_output_CADD_update_gnomad_filtered.txt
done

If I can't successfully filter the CADD_PHRED scores using filter_vep, are there any alternative tools available to do this filtering? Also, it is challenging to filter because the CADD_PHRED scores are not in a separate column, but a grouped in the "Extra" column with other annotation separated by semicolons.

Thanks,
Kevin
[s1_variant_effect_output_CADD_update_cleaned.txt](https://github.com/Ensembl/ensembl-vep/files/14365327/s1_variant_effect_output_CADD_update_cleaned.txt)

**Comment by jamie-m-a** [comment]
Hi @kevin198930

I'm not sure why, but your file is still full or characters that shouldn't be there. You can use linux `od -c` to inspect it yourself.

When I run the sed command I can clean the new file you uploaded and filter_vep runs successfully. At this point I can't offer you much further help as the filter_vep tool is working correctly. I'm not sure that other tools would work correctly for filtering as the output that was selected from VEP was the custom VEP format rather than a more generic format, like VCF. So I'm not aware of other filtering choices (though even if they exist they are likely to be impacted by the issues you have with nonstandard characters in the file).

Looking at you bash script, I'm really not sure what parts of it are trying to do and they may be introducing the random characters.

I ran the following script (must be in same directory as the files) on some dummy files generated based on you example file:

`for file in s1*; do
        sed -e 's/"//g ; s/\r//g' $file > cleaned_$file
        filter_vep -i cleaned_$file --filter "CADD_PHRED > 20" -o CADD_FILTERED_${file};
        done`

Again it worked as expected.

**Comment by jamie-m-a** [comment]
I'm going to close this issue now as there doesn't seem to be much more I can help with, but please reach out to us if you're still having issues with filter_vep.
