### ISSUE TITLE
[Question] What is the definition of "coding_sequence_variant"? Why are frameshifts no coding sequence variant?

### ISSUE THREAD

**Issue by Hoeze** [Ensembl/ensembl-vep#1612]
According to the sequence ontology, frameshift variants are coding sequence variants:
http://sequenceontology.org/browser/current_svn/term/SO:0001818

However, VEP does not annotate them as coding sequence variants, e.g. GRCh37:3:139258442:TG>T.

How exactly does VEP define coding sequence variants?

### System
- VEP version: 111
- online: http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=tGQvfoB7D9H59KrH-9892300

**Comment by jamie-m-a** [comment]
Hi @Hoeze 

VEP utilises Sequence Ontology terms when annotating variants, but it attempts to use the more meaningful term where possible.

frameshift_variant, is a type of protein_altering_variant, which in turn is type of coding_sequence_variant.

If the most specific VEP can be about a variant is to say that it appears in a coding region, then it would report coding_sequence_variant, but if it can be more specific, it will be.

I hope this answers your question, but do get back to me if you have follow up questions.

**Comment by Hoeze** [comment]
Hi @jamie-m-a, thank you for your answer!
Is there some documentation on what gets assigned as coding-sequence-variant?

In theory, any start, stop, frameshift, missense, and synonymous variant would be a CDS variant.
What is there left that is a CDS variant but none of these types?

**Comment by jamie-m-a** [comment]
Hi @Hoeze 

I don't think we have specific documentation about this, beyond what can implied from http://www.ensembl.org/info/genome/variation/prediction/predicted_data.html 

The `coding_sequence_variant` is used as a sort of catch all for variants where there is incomplete information - for example when we provide COSMIC variant data on the Ensembl website, we can only share the variant position and reference allele not the variant alelle ([For example](http://www.ensembl.org/Homo_sapiens/Variation/Explore?r=MT:9562-10562;v=COSV104419734;vdb=variation;vf=1155695667)). In this case we have to use the `coding_sequence_variant` consequence because we can't more precisely define it.

**Comment by jamie-m-a** [comment]
I'm going to close this issue now as I think the explanation has been provided. Do contact us again if you other questions though.
