### ISSUE TITLE
INSTALL.pl - Switch to https?

### ISSUE THREAD

**Issue by sjaenick** [Ensembl/ensembl-vep#1641]
## Describe the issue

INSTALL.pl (which is distributed as vep_install within bioconda) insists on using FTP (https://github.com/Ensembl/ensembl-vep/blob/release/111/INSTALL.pl#L11559) to connect to ftp.ensembl.org. As FTP is nowadays blocked on many firewalls, would you
consider a switch to https://ftp.ensembl.org?

VEP version is 111.0 (Docker container quay.io/biocontainers/ensembl-vep:110.0--pl5321h2a3209d_0) used within
the nf-core sarek workflow (https://github.com/nf-core/sarek).

i experienced a stalled workflow and was able to track this down to VEP (https://github.com/nf-core/sarek/issues/1442), suggested
fix would be a switch to https:// instead of FTP.

`vep_install --CACHEDIR vep_cache --SPECIES homo_sapiens --ASSEMBLY GRCh37 --CACHE_VERSION 110 --AUTO c --CONVERT --NO_BIOPERL --NO_HTSLIB --NO_TEST --NO_UPDATE`

**Comment by jamie-m-a** [comment]
Hi @sjaenick my apologies for not getting back to you sooner, I lost track of this issue.

I hope the workaround was successful for you. I'll look at having the install script updated for a future release of VEP, it might take a little while as we have to test such changes extensively.

**Comment by dvg-p4** [comment]
What exactly is the workaround for this issue?

**Comment by dvg-p4** [comment]
Is this change still planned for an upcoming release?

**Comment by jamie-m-a** [comment]
Hi @dvg-p4 no we are not planning to make this change imminently - one workaround I'd suggest is for you to contact your system administrator and they should be able to unblock the ftp access for you.

Alternatively all the ensembl ftp site is mirrored on globus, for example the current version of the cache you are looking for is: https://g-a8b222.dd271.03c0.data.globus.org/ensemblorg/pub/current_variation/indexed_vep_cache/homo_sapiens_vep_112_GRCh37.tar.gz

**Comment by dvg-p4** [comment]
@jamie-m-a Thanks for the info, but unfortunately neither of those workarounds really solve the issue for me.

> they should be able to unblock the ftp access for you

Blocking FTP is an organizational policy for one of our large customers, I'm pretty sure the decision is at least 2 or 3 levels above me. And it honestly seems a pretty reasonable policy overall, given [the major security risks associated with FTP and the readily available alternatives](https://www.ssh.com/academy/ssh/ftp/server). (Even though in this particular instance, the data is publicly available with no authentication.)

> Alternatively all the ensembl ftp site is mirrored on globus

Good to know there's a mirror, though it's not the domain that's blocked, it's the protocol--so that doesn't really help. I can already manually download files with `wget https://ftp.ensembl.org/...` -- the issue is that I can't do it automatically with the INSTALL.pl script. So I'm not totally blocked here, but it's a major pain every time I need to set up a VEP install for a new version or site.

**Comment by jamie-m-a** [comment]
Ah I see @dvg-p4 - I hadn't fully appreciated your situation. I will raise a ticket for adding it as an option for the install script - thanks for clarifying.

**Comment by jamie-m-a** [comment]
We have an intention to add this functionality - though I can't say for certain when it will be available. As such I will close this ticket now, but please do reach out if you have any other questions.
