### ISSUE TITLE
Haplo results interpratation

### ISSUE THREAD

**Issue by Jokendo-collab** [Ensembl/ensembl-vep#1655]
I am getting the following results with `haplo` analysis:
```bash
138	TL_T12:2	
12	TL_T12:2,TL_T24:1	
1	TL_T12:2,TL_T24:1,WIK_T12:2,WIK_T24:1	
6	TL_T12:2,TL_T24:2	
2	TL_T12:2,TL_T24:2,TL_T6:2	
1	TL_T12:2,TL_T6:1	
2	TL_T12:2,TU_T12:1	
2	TL_T12:2,TU_T12:2	
4	TL_T12:2,WIK_T12:1	
9	TL_T12:2,WIK_T12:2	
850	TL_T24:1
```
What is the difference in  `TL_T12:2	` and  `TL_T24:1`  how do I make sense of this? Do these numbers after the `:` have a significant meaning that I need to tell a story?

**Comment by nuno-agostinho** [comment]
Hi @Jokendo-collab,

Thank you for your interest in using Haplosaurus (`haplo`)!

Those results are comma-separated lists of `sample:count` (i.e., the count number for each sample) that exhibit the haplotype described. For more information on using and interpreting Haplosaurus, please read our [public documentation](https://www.ensembl.org/info/docs/tools/vep/haplo/index.html).

Hope this makes it clearer, but tell me if otherwise.

Kind regards,
Nuno

**Comment by nuno-agostinho** [comment]
Hey @Jokendo-collab,

I will now close this issue, but feel free to open a new one in case you need further clarification.

Thank you!

Best regards,
Nuno
