### ISSUE TITLE
You must specify a region in the format chr, chr:start or chr:start-end at  perl5/5.32/site_perl/Bio/DB/HTS/Tabix.pm line 104

### ISSUE THREAD

**Issue by xmy1990** [Ensembl/ensembl-vep#1660]
When I use vep to annoate a hg38.vcf , an error appeared,

You must specify a region in the format chr, chr:start or chr:start-end at  perl5/5.32/site_perl/Bio/DB/HTS/Tabix.pm line 104.

I don't know how to debug it ,

A same quesion before :https://github.com/Ensembl/ensembl-vep/issues/789
But no ":" in my hg38.vcf variants.

Could you please give me some advice！
Thanks

**Comment by olaaustine** [comment]
Hi @xmy1990, 

Hope you are well?
Thank you for your query 

If possible can you share the VCF file used so we can try to recreate this issue, also to figure out if the issue is the input file, can you run VEP using this [input file](https://github.com/Ensembl/ensembl-vep/blob/release/111/examples/homo_sapiens_GRCh37.vcf) and the `--assembly GRCh37`. 

Hoping to hear from you soon. 
Thank you 
Ola.

**Comment by xmy1990** [comment]
The same error exists with this vcf：https://github.com/Ensembl/ensembl-vep/blob/release/111/examples/homo_sapiens_GRCh37.vcf

For this error: “You must specify a region in the format chr, chr:start or chr:start-end at perl5/5.32/site_perl/Bio/DB/HTS/Tabix.pm line 104”,  did it mean the #CHROM in my vcf did not have "chr"  or other region?


My vcf like this:
chr1    86282   .       T       G       82.19   PASS    AC=1;AF=0.00066;AN=1516;BaseQRankSum=1.121;DP=4113;Dels=0.00;FS=4.450;HRun=0;HaplotypeScore=0.1230;InbreedingCoeff=-0.0713;MQ=50.47;MQ0=377;MQRankSum=-0.472;QD=15.00;ReadPosRankSum=-0.047;SB=-31.80;VQSLOD=5.1323;pop=ALL
chr1    86331   rs115209712     A       G       15414.55        PASS    AC=218;AF=0.12616;AN=1728;BaseQRankSum=-4.790;DB;DP=4696;Dels=0.00;FS=0.922;HRun=2;HaplotypeScore=0.1808;InbreedingCoeff=0.0185;MQ=58.01;MQ0=1;MQRankSum=-7.246;QD=11.72;ReadPosRankSum=1.185;SB=-5186.86;VQSLOD=5.4426;pop=ALL
