### ISSUE TITLE
Failed to instantiate plugin dbNSFP: ERROR: Could not retrieve dbNSFP version from filename

### ISSUE THREAD

**Issue by yougulianren** [Ensembl/ensembl-vep#1667]
Dear,

I am running VEP using dbNSFP plugin like this:

docker run --rm -v /project/WGS-CN1:/work -v /project/
CN1.v0.8:/ref ensemblorg/ensembl-vep:latest vep -i /work/JX4.fam.final.vcf.gz --fasta /ref/CN1_combine.v0.8.fasta --plugin dbNSFP,/ref/CN1_v0.8_swapped_hg38_dbNSFP33a.txt.gz,ALL --fork 1 --compress_output bgzip --individual_zyg all --symbol --force_overwrite -o /work/JX4/02.snv.annotation/family/JX4.fam.db.anno.txt.gz  --database

But I get an error:

       WARNING: Failed to instantiate plugin dbNSFP: ERROR: Could not retrieve dbNSFP version from filename /ref/CN1_v0.8_swapped_hg38_dbNSFP33a.txt.gz

How to solve the problem with this plugin?

**Comment by nakib103** [comment]
Hello @yougulianren,

Thanks for your query!

dbNSFP data file generally have version like `X.Y` - for example `dbNSFP4.3a.zip`.  We derive the version from the filename - you are seeing that error because the file you are using does not have version in this format (33a with no `.`). 
Your files does not seem like a standard dbNSFP file. Where did you get this file? You can try renaming the file to `CN1_v0.8_swapped_hg38_dbNSFP3.3a.txt.gz` and see if that works.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hello @yougulianren,
I will close this issue, if you face further problems please feel free to open a new one.
