### ISSUE TITLE
Use extracted data against of compressed [QUESTION]

### ISSUE THREAD

**Issue by GhorbaniAli** [Ensembl/ensembl-vep#1692]
Is there a way to make the data files uncompressed?

### Examples
```shell
# Current
•/vep -i variants.txt -o variants_output.txt --gff 'data-gff.gz' --fasta 'genome.fa.gz'
# Requested
•/vep -i variants.txt -o variants_output.txt -gff 'data.gff' --fasta 'genome.
```
or
```shell
# Current
•/vep --cache -i variants.vcf --custom file='phenotypes.bed.gz', short_name=phenotype
# Requested
•/vep --cache -i variants.vcf --custom file='phenotypes.bed', short_name=phenotype
```
or
```shell
# Current
....... -plugin dbNSFP, 'dbNSFP4.7a.txt.gz'
# Requested
....... -plugin dbNSFP, 'dbNSFP4.7a.txt'
```
or
```shell
....... --custom file='clinvar_20240514.vcf.gz',short_name=ClinVar,format=vcf,type=exact,coords=0
# Requested
....... --custom file='clinvar_20240514.vcf',short_name=ClinVar,format=vcf,type=exact,coords=0
```

**Comment by nuno-agostinho** [comment]
Hey @GhorbaniAli,

Thanks for your question.

VEP does not accept uncompressed files because of Tabix: Tabix only supports bgzipped files and indexed files are required to quickly transverse through files. It would not be efficient to use non-indexed files.

Hope this information makes it clearer.

Kind regards,
Nuno

**Comment by nuno-agostinho** [comment]
Hi @GhorbaniAli,

Hopefully the previous answer was helpful, but please reply back if you'd like further clarification.

I will close this issue now.

Cheers,
Nuno
