### ISSUE TITLE
Can't use filter_vep subfields in the tab separated vep output file

### ISSUE THREAD

**Issue by tamil-acog** [Ensembl/ensembl-vep#1761]
Hi team, 

I annotated my variants using vep with spliceAI plugin. The output file contains all the multiple columns along with SpliceAI_pred column. 

But the values in the column for a variant, for example "FGFR3 | 0.0 | 0.2 | 0.0 | 0.0 | 180"

Now if I have to filter the output based on the third field which 0.2 in the above example, how can i do that? 

Thanks in advance

**Comment by nakib103** [comment]
Hello @tamil-acog,

Thanks for your query!

You can filter your VEP output using filter_vep tool. For example, if the third field in this case have name `SpliceAI_pred_DP_DG` and you want outputs that have `SpliceAI_pred_DP_DG` value greater than 0.2 you can do that by using the following commands -

```
filter_vep -i input.vcf --filter "SpliceAI_pred_DP_DG > 0.2" --format vcf --only_matched
```

Please check the [filter_vep](https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html)  document to build appropriate filter for your need.

Best regards,
Nakib

**Comment by nakib103** [comment]
@tamil-acog , 
sorry I missed you were talking about tab separated output. Currently it is not possible to use filter_vep on specific SpliceAI fields in tab separated output because the fields are reported all in the same field.

So you can output using VCF format and use the above command to filter.
Otherwise, there is a [PR](https://github.com/Ensembl/VEP_plugins/pull/721) that separates the the SpliceAI fields in the output, which you can cherry-pick and see if it resolves your use case.

Best regards,
Nakib

**Comment by nakib103** [comment]
Hi @tamil-acog,

I will be closing this issue. If you face any further problems feel free to open a new one.
