### ISSUE TITLE
Missing gnomAD Frequency Values for a Variant in Ensembl VEP

### ISSUE THREAD

**Issue by mrymkdnz** [Ensembl/ensembl-vep#1803]
I ran a variant through Ensembl VEP, and you can view the results here: https://www.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=uiEVKf6hiWhXE2Og-10660152. However, I noticed that the gnomAD frequency values are missing for this variant.

When I searched for the same variant on the gnomAD website (https://gnomad.broadinstitute.org/variant/7-95316772-A-T?dataset=gnomad_r4), I found that frequency values are present, and the filter status is "PASS."

Could you clarify the reason for this discrepancy? Is there an issue with the data integration between Ensembl VEP and gnomAD, or could there be another explanation for this missing information?

Thank you for your help!

### System
- VEP version: v113
- VEP Cache version: 113_GRCh38
- OS: vep launch
### Full VEP command line
```
./vep --af_gnomade --af_gnomadg --appris --biotype --buffer_size 500 --check_existing --distance 5000 --mane --polyphen b --pubmed --regulatory --show_ref_allele --sift b --species homo_sapiens --symbol --transcript_version --tsl --uploaded_allele --cache --input_file [input_data] --output_file [output_file]
```

**Comment by dglemos** [comment]
Hi @mrymkdnz,
The correct input format is `7 95316772 95316772 A/T`.
Also, in Ensembl this variant  has been flagged because of ambiguity in the allele codes: https://www.ensembl.org/Homo_sapiens/Variation/Explore?db=core;r=7:95316272-95317272;v=rs854560;vdb=variation;vf=480715206
When you run the VEP job you should select the option "Include flagged variants".
You can check more details in this job: https://www.ensembl.org/Homo_sapiens/Tools/VEP/Ticket?tl=VWmGwpQeP2DiAv54

**Comment by dglemos** [comment]
If a variant is flagged, VEP will not return co-located variants or their associated subcomponent data, such as gnomAD data in this case.

**Comment by mrymkdnz** [comment]
thank you
