### ISSUE TITLE
Population frequency fields empty with --filter_common

### ISSUE THREAD

**Issue by loreseeker** [Ensembl/ensembl-vep#249]
Hello,

with ensembl-vep 90.5 (also with 92.5) and Ensembl VEP caches 90 and 91 (GRCh37, processed with convert_cache.pl) and --everything I've noticed that toggling --filter_common option on leaves population frequency fields empty (1000g, ESP, gnomAD) and that a variant that I expected to be filtered out remains in the output file. Toggling this option off displays values normally. I don't usually use this option (using filter_vep script instead), so I could be doing something wrong, but here's a minimal variant example to reproduce:
17 7579472 . G C

It occurred to me that the option maybe simply doesn't write the values (is filtering them out) but I was expecting for the whole variant row to be excluded from the output. It's quite possible that I am misunderstanding the expected behaviour.

Thank you for your time.

**Comment by ens-lgil** [comment]
Dear @loreseeker,

Thank you for reporting this issue and thank you for the example.
The `--filter_common` flag is definitely not behaving as expected in this particular example.
We are investigating it.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @loreseeker,

We just added a fix concerning the empty population frequencies on VEP 93.2.

The fact that this particular variant is not filtered out is a bit more complicated: 
The `--filter_common` flag gets (by default) the 1000Genomes minor allele frequency.
In your example, the variant is co-located with `rs1042522 (G/**C**/**T**)`, which has 2 alternate alleles.
The minor allele data we have from 1000Genomes is `G (0.4571)`, which means that we don't have the global frequency of `C`. Unfortunately, in this case we can't do the simple calculatation `1 - 0.4571` as it will gives us the combination of the `C` and `T` frequencies, and we are only interested in the allele `C`.

Because we can't give a global frequency for `C`, we can't filter out this entry, just in case the allele `C` is associated with a very low frequency.

I hope this makes sense.

Best regards,
Laurent

**Comment by loreseeker** [comment]
Dear Laurent,

thank you for the detailed explanation for this specific case (it makes sense :)) and for the implemented fix.  I'll close the ticket.

Regards,
Jelena
