### ISSUE TITLE
Haplosaurus: frameshift causing reference stop codon to be lost AND splice site variants

### ISSUE THREAD

**Issue by iranmdl** [Ensembl/ensembl-vep#286]
Hello!
If a given frameshift causes the downstream reference stop codon to be lost, when does the translation of the protein stop?

Another more general question, how are the splice site variants handled? Is it possible to generate new isoforms using haplosaurus?

Thank you in advance,
Ira

**Comment by ima23** [comment]
Hi @iranmdl,

Apologies for the delay. 
For your first question: it depends very much on the gene and protein you are looking at. The translation will stop at the first encountered STOP codon.
For your second question: I'm not sure I understand what you mean by 'generate new isoforms'
I would appreciate if you could give a few examples of what you are looking at to help me understand what you mean.

Thanks,
Irina

**Comment by iranmdl** [comment]
Hello!
Sorry for the delay as well on my side :).
Thank you for the STOP lost question, cristal clear :). And forget about my second question :)

I have another question though. I have run `haplosaurus` and for some variants I get `contributing_variants` field empty for the `protein_haplotypes` but with variant ID in `cds_haplotypes` `contributing_variants` field.
Example, input.vcf:

> chr1	152114079	chr1_152114080_-/T	A	AT	.	cons_2	VS=S;VAF=0.06;VCn=3;fb=0;la=1;m2=0;ss=0;s2=1;vd=1;v2=0;CSQ=T|frameshift_variant&start_lost&start_retained_variant|HIGH|TCHH|ENSG00000159450|Transcript|ENST00000368804|protein_coding|1/2||||1-2|1-2|1|M/NX|atg/aAtg|rs748146582||-1||insertion|HGNC|HGNC:11791||5|P1|CCDS41396.1|ENSP00000357794|Q07283||UPI0000458A5E|||Ensembl||||1|ENSG00000159450|||hmmpanther:PTHR34855&Superfamily_domains:SSF47473|||||||||0.0005133|0.0005122|0.0008436|0.000524|0.000568|0.0005698|0.0004827|0|0.0003016|0.0008436|gnomAD_AMR||||||||,T|frameshift_variant&start_lost&start_retained_variant|HIGH|TCHH|ENSG00000159450|Transcript|ENST00000614923|protein_coding|2/3||||96-97|1-2|1|M/NX|atg/aAtg|rs748146582||-1||insertion|HGNC|HGNC:11791|YES|5|P1|CCDS41396.1|ENSP00000480484|Q07283||UPI0000458A5E|NM_007113.3||Ensembl||||1|ENSG00000159450|||hmmpanther:PTHR34855&Superfamily_domains:SSF47473|||||||||0.0005133|0.0005122|0.0008436|0.000524|0.000568|0.0005698|0.0004827|0|0.0003016|0.0008436|gnomAD_AMR||||||||,T|frameshift_variant&start_lost&start_retained_variant|HIGH|TCHH|7062|Transcript|NM_007113.3|protein_coding|2/3||||96-97|1-2|1|M/NX|atg/aAtg|rs748146582||-1||insertion|EntrezGene|HGNC:11791|YES||||NP_009044.2|||||rseq_mrna_match|RefSeq|||||ENSG00000159450||||||||||||0.0005133|0.0005122|0.0008436|0.000524|0.000568|0.0005698|0.0004827|0|0.0003016|0.0008436|gnomAD_AMR||||||||	GT:AD	0/1:135,8

Here you can find `haplosaurus` result for that variant. As you can see, contributing_variants field is empty for `protein_haplotypes`, is that expected?
[ex_missing_contr_var.json.zip](https://github.com/Ensembl/ensembl-vep/files/2465524/ex_missing_contr_var.json.zip)

Thank you again :)

**Comment by ima23** [comment]
Hi @iranmdl,

Glad to hear your previous questions are now answered.
Thanks for the example relating to your new question. Haplosaurus works with phased genotype data (phased example would be GT 0|1) while the shown input is unphased (GT 0/1).  If you want to find out more about the VCF format and genotype field, the link below provides detailed info http://www.internationalgenome.org/wiki/Analysis/vcf4.0/.

Glad I could help,
Irina

**Comment by iranmdl** [comment]
Hello!
I realize that `haplosaurus` work better with phased data... but with unphased data it also produces the mutated protein or cds sequence. See in the example I have sent you. The mutation is an insertion in position 2 of the CDS. In the REF CDS you can see the reference sequence (ATGTCT..) while in the mutated CDS you see the insertion (A**A**TGT...). So it is working, isn't it?

In the protein_haplotype, you can see as well the consequence of the insertion. giving in "seq" field the protein sequence: "NVSTSEKHL*", I'm not sure how this is computed though. However, my question is that "contributing_variants": [] is empty in the mutated protein field but not in the mutated CDS field.
Does it make any sense?
I know what is phased data, thanks, I'm just curious about `haplosaurus` behaviour without phased data.

Just to double check what I mean. I have run again haplosaurus with that unique variant and I have changed `0/1` to `0|1`. The result is the same :), I can attach the json but is exactly the same as the previous one. And makes sense that is completely equal because if you have only one variant affecting to a transcript and that variant is heterozygous, it does not matter if it is 0|1 or 0/1, the product (protein/transcript) will be mutated for one allele but not for the other in both cases.

Let me know if I'm not explaining the issue properly or you need more info.
And thank you again,
Ira

**Comment by ima23** [comment]
Hi Ira,

Thanks for the details.
 
I understand you want to repurpose `haplosaurus` functionality for unphased data. Even if it might give the correct results, this is not the use case for which it was developed and tested. It will also take a lot more time to compute the results as for each variant multiple sequences will be computed either containing only that variant or being the reference sequence. Please use it for phased data as this is the only currently supported input format, see online documentation: http://www.ensembl.org/info/docs/tools/vep/haplo/index.html.

Yes, you are correct, given the specific 1 variant in 1 sample example,`haplosaurus` gives the same results for phased or unphased data. Contributing_variants get reported for `protein_haplotypes`, but indeed in this case the array is empty. This is due to the protein change being mistaken for a complex event, the reference 1,945 amino acid protein is truncated down to 9 amino acids.
A big difference between the reference and the new sequence can hide complex events which are more complicated to tease out and will lead to `contributing_variants` array being empty. In the example there was only 1 variant, so yes, there is definitely space for improvement here and we will look into a fix for this. Thanks for finding it!

Relating to the `protein_haplotype` question, the sequence "NVSTSEKHL*" is the 5'3' frame 1 translation of the transcript sequence containing the variation (`ENST00000368804:2insA` in your example). 

As a note, for simpler events / more straight forward events, the `contributing_variants` for `protein_haplotypes` will be displayed correctly, for example:
> #CHROM    POS    ID    REF    ALT    QUAL    FILTER    INFO    FORMAT    IND1    IND2
> 12    6029429    rs1800380    C    T    .    .    .    GT    1|0    1|1
> 12    6029431    rs370984712    G    A    .    .    .    GT    1|0    1|1 

Best wishes,
Irina

**Comment by jamie-m-a** [comment]
Response from Irina seems appropriate, no further follow up so I'm closing this one off.
