### ISSUE TITLE
Ensembl VEP on Flathub

### ISSUE THREAD

**Issue by PlatonB** [Ensembl/ensembl-vep#287]
It takes a long time and effort to resolve all dependencies manually (personally, I'm using Fedora). Please, place Ensembl VEP on flathub.org

**Comment by at7** [comment]
Hello,
VEP is not a desktop application but a command line tool. Which is why I don't think that flathub is the right platform for distributing VEP. We do have a docker [image](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker) which you could try using. We are also constantly working on improving the installation of VEP and we are providing documentation for helping with the installation steps. Please let us know if there is anything you found particularly difficult.
Thanks,
Anja

**Comment by PlatonB** [comment]
> VEP is not a desktop application but a command line tool. Which is why I don't think that flathub is the right platform for distributing VEP.

Placing in modern app store would help not only simplify installation but also popularize Ensembl VEP and bioinformatics in general.

> Please let us know if there is anything you found particularly difficult

It is especially unpleasant to resolve the Bio::DB:HTS dependency. Generally, I think manual resolution of dependencies is archaic way in 2018.
