### ISSUE TITLE
failed installation or running

### ISSUE THREAD

**Issue by drtamermansour** [Ensembl/ensembl-vep#30]
default installation failed with this error message:
Compile didn't complete. No libhts.a library file found at INSTALL.pl line 748.

I tried installation with:
perl INSTALL.pl --NO_HTSLIB

Now the installation is working but when I tried to run my prediction command:
perl $HOME/ensembl-vep/vep.pl -i my.vcf -gff data.gff.gz -fasta $genome

I got this exception:
MSG: ERROR: Cannot use format gff without Bio::DB::HTS::Tabix module installed

**Comment by ens-lgil** [comment]
@drtamermansour, unfortunately HTSLIB is required to read from GFF format.
Apparently, something when wrong during the automated installation of htslib through the VEP installation script.
Please, could you try to install htslib manually ?
Here is the download command: git clone -b 1.3.2 https://github.com/samtools/htslib.git
And the installation instructions: https://github.com/samtools/htslib/blob/develop/INSTALL

Cheers,
Laurent

**Comment by ens-lgil** [comment]
Dear @thedam,

Did you install Bio::DB::HTS manually ?
If so, you might need to add the library to you PERL5LIB variable (in your .bashrc for instance):
`PERL5LIB=${PERL5LIB}:/home/damian/ensembl_src/Bio-DB-HTS/lib
export PERL5LIB`

You can check if it's in your PERL5LIB by running the following command:
`perl -e "use Bio::DB::HTS::Tabix"`

Best regards,
Laurent

**Comment by thedam** [comment]
Hi,
Thanks for answer. Yes, I had exported these libraries. I can't check now if `perl -e "use Bio::DB::HTS::Tabix"` since I was so frustrated that I've removed everything and finally learned how to use Docker. I leave here my commands for the future generations.

Pull Docker Vep:
`docker pull ensemblorg/ensembl-vep`

run Docker-Vep with volumes where I keep my data:

`docker run -t -i -v /paht/on/my/host/vepCache:/home/vep/.vep  -v  /paht/on/host/gnomAD:/home/vep/gnomAD  -v /mnt/ssd_01/VEP/tests:/home/vep/tests ensemblorg/ensembl-vep /bin/bash`

-v option maps storage on your host with a path in Docker
`-v /full/path/on/host:/full/path/on/dockerVep`
(mind that you have to grant permission to `/full/path/on/host` to be able to save the data from docker)

then I was able to run the command that without docker didn't work (access gnomAD's vcf file):
`vep -i test.vcf --cache --refseq -o test16.csv  --port 3337 --tab --ASSEMBLY GRCh37 -custom /home/vep/gnomAD/gnomad.exomes.r2.0.1.sites.noVEP.vcf.gz,gnomADe,vcf,exact,0,AF_NFE,POPMAX,AF`

**Comment by ens-lgil** [comment]
Dear @thedam,

I am sorry to hear that the VEP installation was difficult. The use of htslib is quite important to speed up VEP, mainly when the custom annotation files are big.
We recommand to install htslib and the Perl moduel Bio::DB::HTS through the VEP `INSTALL.pl` script as it tries to install everything at the right place.

We don't advertise much about the VEP Docker installation, but this is so far the easiest way to install VEP. And I am glad that it finally worked for you!

Out of curiosity, did you look at the VEP Docker documentation to install it ?
http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker

Best regards,
Laurent

**Comment by thedam** [comment]
yes, I took the inspiration exactly from this page :)
But they could mention that it's important to set right privileges to docker and host paths :+1:

**Comment by ens-lgil** [comment]
@thedam, thank you for the feedback/suggestion!
I just updated the VEP web documentation to make it more clear about the setting write access to the host directory so Docker can read the input files and write the VEP output.
This should be visible on the website at the end of the week when the new Ensembl release will be live (92).

Best regards,
Laurent

**Comment by thedam** [comment]
Great, the more useful hints, the more happy users:)
Also would be nice to add some hints how to easily update for a newer Docker-VEP version, and if the cache should be overwritten, and stuffs like that.
Cheers!

**Comment by kjohnsen** [comment]
Thank you thedam, I too have had a very frustrating experience trying to install VEP right. I don't want to think about how many hours I've dedicated to it. I wish I had just used Docker sooner!
