### ISSUE TITLE
Feature request: convert VCF to TAB

### ISSUE THREAD

**Issue by fgvieira** [Ensembl/ensembl-vep#346]
It would be nice if there was a way to convert VCFs annotated by VEP to tab format. It could be just adding the option `-tab` to `filter_vep` (and the user could just run it without filters if just wanted to convert).

I know VEP can output in TAB (`--tab`), but sometimes you just don't want to keep annotating files just to convert the format.

**Comment by ens-lgil** [comment]
Dear @fgvieira,

Thank you for the feature suggestion!
We keep track of the users suggestions and the frequently requested features are often implemented.
Bear in mind that it might take some time to implement it, mainly because of other features already planned and our release cycle (~3 months).

Best regards,
Laurent

**Comment by fgvieira** [comment]
I've been looking into this, and it seems it should be possible to make using Ensemble VEP perl modules.
However, I've been having some issues getting it to properly read the VCF. Here is what I have so far:

```
use Bio::EnsEMBL::VEP::Config;
use Bio::EnsEMBL::VEP::Parser::VCF;
use Bio::EnsEMBL::VEP::InputBuffer;
use Bio::EnsEMBL::VEP::OutputFactory::JSON;

my $cfg = Bio::EnsEMBL::VEP::Config->new();

my $vcf_file = 'test.vcf';
my $p = Bio::EnsEMBL::VEP::Parser::VCF->new({config => $cfg, file => $vcf_file});
my $ib = Bio::EnsEMBL::VEP::InputBuffer->new({config => $cfg, parser => $p});

my $of = Bio::EnsEMBL::VEP::OutputFactory::Tab->new({config => $cfg,});
# Print headers                                                                                                                                                                                                
print "$_\n" for @{$of->headers};
# Print output                                                                                                                                                                                                     
print "$_\n" for @{$of->get_all_lines_by_InputBuffer($ib)};
```

Am I missing something?
Is the `$cfg` variable needed? If so, what should it contain?

thanks,

**Comment by at7** [comment]
Have you tried [vcf-to-tab](https://vcftools.github.io/perl_module.html#vcf-to-tab) which is part of VCFtools?

**Comment by willmclaren** [comment]
Neither your code nor vcf-to-tab will convert VCF-encoded VEP output to the default tab-delimited VEP output, which is what I assume @fgvieira requires.

Your best bet for starting some code would be to look at [`filter_vep`](https://github.com/Ensembl/ensembl-vep/blob/master/filter_vep), which contains code for parsing the VEP results encoded in VCF.

I had a quick hack at `filter_vep` recently attempting a similar thing (trying to convert to JSON), here it is in a Gist: https://gist.github.com/willmclaren/95ffc7a6479a9dc9eb937fc80754b6cf . At the moment all it does is parse the VCF line into a nested hash structure, but you should be able to work from the `Data::Dumper` lines to get to what you want.

**Comment by willmclaren** [comment]
The keys are renamed according to [this hash](https://github.com/Ensembl/ensembl-vep/blob/master/modules/Bio/EnsEMBL/VEP/OutputFactory/JSON.pm#L98-L111); see the rest of that module for a clue as to how the standard output data structure is re-structured into JSON. Apart from the labels there are a few other differences between the JSON and other formats. 

The standard SIFT output is just a combination of the score and prediction written as `prediction(score)` (assuming you're using `--sift b`, see the [flag docs](http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_sift) for more info).

I'm currently working towards getting VEP to output both VCF and JSON in the same run rather than post-converting one to the other (it's easier to avoid data loss or horrible refactoring this way); this will likely take the form of a plugin to generate the JSON alongside the main VCF output. I can post the results here if they're worth doing so :-)

**Comment by thedam** [comment]
https://knausb.github.io/vcfR_documentation/

**Comment by susannasiebert** [comment]
You might be interested in the vep-annotation-reporter that is part of VAtools (vatools.org). Given a VCF and a list of VEP fields it will convert the VCF entries to TSV and append the selected VEP fields as individual columns.

**Comment by aiqc** [comment]
After exploring several dead ends in the form of output formats and parsing tools – I've come to the conclusion that there's really no good choice for an output format. 

You can either: 

- Jam loosely defined `|` delimited vep annotations into your VCF INFO field. The vep schema provided in the file header doesn't match the actual data entries.
- Or ultimately lose your VCF INFO/FORMAT columns during parsing

The path I recommend is generating tabular VEP output and then **_joining_** it to the original VCF by position. 


### Harmonize tabular VEP with VCF INFO and FORMAT columns

```python
import pandas as pd
file_id = "[YOUR_FILE_ID]"


## ====== VEP FILE ======
vep_file = f"{file_id}.vep"

# Figure out what line the real data starts at
with open(vep_file) as f:
    lines = f.readlines()
header_prefix = "#Uploaded_variation"
for i, line in enumerate(lines):
    if (line.startswith(header_prefix)): 
        # Don't worry about zero-based index
        vep_headerNum = i
        break

df_vep = pd.read_csv(vep_file, sep='\t', header=vep_headerNum)

locations = df_vep['Location']

# VEP uses `chrom:pos`, but VCF uses separate columns
chroms = [location.split(':')[0] for location in locations]

# VEP uses `start-stop`, but VCF only uses `start`
positions = [location.split(':')[1].split('-')[0] for location in locations]

df_vep['CHROM'] = chroms
df_vep['POS'] = positions
df_vep = df_vep.astype({'POS':'int64'})


## ====== VCF FILE ======
vcf_file = f"{file_id}.qc.vcf"

# Figure out what line the real data starts at
with open(vcf_file) as f:
    lines = f.readlines()
header_prefix = "#CHROM"
for i, line in enumerate(lines):
    if (line.startswith(header_prefix)): 
        # Don't worry about zero-based index
        vep_headerNum = i
        break

df_vcf = pd.read_csv(vcf_file, sep='\t', header=2806)
df_vcf.rename(columns={header_prefix:'CHROM'},inplace=True)


## ====== JOIN ======
df_harmonized = df_vep.merge(df_vcf, on=['CHROM','POS'], how='left')
df_harmonized.to_csv(sep='\t',index=False)

if (df_harmonized.shape[0]) != (df_vep.shape[0]):
    raise Exception('failed to match all rows')

# rearrange and deduplicate your columns as you see fit
```

I hope this demonstrates the value of columnar data in Python

**Comment by aiqc** [comment]
# Tabular Parser

Wrote a parser because I couldn't find a way to get tabular VEP data that preserves the original VCF positional, INFO, and FORMAT data. It's dynamic in that it adjusts to the fields and headers you are using in vep and vcf. The only package it uses is pandas. I provided the code to make the nested VCF fields tabular as well.

<br/><br/>

For context, I'm using the VEP Docker image with these options (offline, vcf, latest gnomad).
```bash
vep -i [in_vcf] -o [out_vcf] --cache --offline --no_stats --quiet --vcf --symbol --pick --af_gnomadg --polyphen b --sift b
```

<br/><br/>

## Tabular VEP Fields

There is a line in the vcf header that will look something like this depending on the fields you use:

```
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|DISTANCE|STRAND|FLAGS|SYMBOL_SOURCE|HGNC_ID|SIFT|PolyPhen|gnomADg_AF|gnomADg_AFR_AF|gnomADg_AMI_AF|gnomADg_AMR_AF|gnomADg_ASJ_AF|gnomADg_EAS_AF|gnomADg_FIN_AF|gnomADg_MID_AF|gnomADg_NFE_AF|gnomADg_OTH_AF|gnomADg_SAS_AF|CLIN_SIG|SOMATIC|PHENO">
```

Let's parse whatever fields we have out of vcf INFO and turn them into columns

```python
import pandas as pd

case_id = 'YOUR_CASE_ID'
file_path = f"{case_id}.anno.vcf"

prefix_schema = "Ensembl VEP. Format: "

with open(file_path) as f:
    lines = f.readlines()

# Extract VEP schema from file header
for line in lines:
    if (prefix_schema in line):              
        # We want everything after format and before closing syntax – broken into list
        vep_cols = line.split(prefix_schema)[1].split('">')[0].split('|')
        vep_cols = [f"VEP_{c}" for c in vep_cols]
        break

# We know the name of the first vcf column
prefix_cols = "#CHROM"

# Find the line number of the vcf columns
for i, line in enumerate(lines):
    if (line.startswith(prefix_cols)): 
        # Pandas wants line number - 1 so don't worry about zero-based index
        header_lineNum = i
        break

df_vcf = pd.read_csv(file_path, sep='\t', header=header_lineNum)
df_vcf.rename(columns={'#CHROM':'CHROM'}, inplace=True)

# everything before `;CSQ=` becomes INFO col and after becomes VEP col
df_vcf[['INFO', 'VEP']] = df_vcf['INFO'].str.split(';CSQ=', 1, expand=True)

# explode the new VEP col
df_vcf[vep_cols] = df_vcf['VEP'].str.split('|',expand=True)
df_vcf = df_vcf.drop(columns=['VEP'])
```

<br/><br/>

## [Optional] Tabular VCF FORMAT Fields

Format was the same for all of my files, but just to be proactive I check it

```python
if (len(df_vcf['FORMAT'].value_counts()) == 1):

    format_cols = df_vcf['FORMAT'][0].split(':')
    format_cols = [f"FORMAT_{c}" for c in format_cols]
    
    df_vcf[format_cols] = df_vcf[case_id].str.split(':',expand=True)
    df_vcf = df_vcf.drop(columns=[case_id, 'FORMAT'])
else:
    print("Warning – FORMAT not be exploded because format fields are not the same for all variants")
```

<br/><br/>

## [Optional] Tabular VCF INFO Fields

This handles sparsity. Some of my files weren't using the same fields

```python
# since they are sparse, we have to parse the rows individually
# it's easy to make a df from a dict

info_entries = []

for row in df_vcf['INFO']: 
    row_pairs = dict(item.split("=") for item in row.split(";"))
    info_entries.append(row_pairs)

df_info = pd.DataFrame.from_dict(info_entries)

info_cols = df_info.columns.tolist()
info_colsRename = [f"INFO_{c}" for c in df_info.columns.tolist()]
renames = dict(zip(info_cols, info_colsRename))
df_info = df_info.rename(columns=renames)

# merge back with the main df
df_vcf = pd.concat([df_vcf, df_info], axis=1)
df_vcf = df_vcf.drop(columns=['INFO'])
```

<br/><br/>

## Save It

```python
df_vcf.to_csv(f"{case_id}.tab.anno.vcf", sep='\t', index=False)
```

**Comment by olaaustine** [comment]
Hi @Hoeze, 
Hope you are well? 
Following discussions with the team, we have decided this is beyond the scope of Ensembl Variant Effect Predictor as a tool. 
Please let us know if you have any other issues. 
Thank you. 
Ola.
