### ISSUE TITLE
Outdated gene names for GRCh37

### ISSUE THREAD

**Issue by marc-sturm** [Ensembl/ensembl-vep#426]
Hi,

we noticed that some gene names are outdated when using VEP on GRCh37.

For example, this variant in the MYORG gene is anntotated with the old gene name:
![grafik](https://user-images.githubusercontent.com/5638144/55066346-e6832800-507d-11e9-85f3-624d63fb95b0.png)

When using GRCh38, MYORG is correctly returned as gene name.

For diagnostics, it would be important to have current gene names according to HGNC:
https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:19918

Is a gene name update planned for GRCh37?

Best,
  Marc

**Comment by ens-lgil** [comment]
Dear @marc-sturm,

The GRCh37 Ensembl geneset hadn't been updated since the release 76, therefore the HGNC gene symbols hadn't been updated since then.
We only update the variant and regulation data once or twice a year.

However VEP provides the HGNC IDs (which don't change over time), and I would recommend to use them over the HGNC symbols.
To be honest we had similar issues on other side projects when we used the HGNC gene symbols as gene identifiers and some of them changed and created some internal issues.
Now we preferably use the HGNC IDs as gene identifiers.

Best regards,
Laurent

**Comment by marc-sturm** [comment]
Hi Laurent,

thanks for the info. I will use the HGNC identifiers then.

Best regards,
  Marc
