### ISSUE TITLE
Bioconda recipe for ensembl vep

### ISSUE THREAD

**Issue by matthdsm** [Ensembl/ensembl-vep#50]
Hi Will,

I've taken the liberty of creating a [conda](https://conda.io/docs/) [recipe](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/ensembl-vep) for vep. I (and others) have been using this to easily install vep.

I was wondering if you're interested in checking out the recipe and providing some comments and suggestions to make it better. It would also be very helpful if you could help keep this recipe up to date with the latest release of vep.

I'd love to hear your thoughts on this.
Thanks
Matthias

**Comment by matthdsm** [comment]
Hi Will,

regarding the bioconda recipe, the Bio:DB:HTS module isn't installed by the vep installer, because this causes issues downstream. However, VEP doesn't seem to detect the externally installed Bio:DB:HTS module. Is there a way to make vep look for this module in another place than the default directory?

thanks
M

**Comment by willmclaren** [comment]
Excellent, I'm glad that others are contributing to getting VEP working in all these different environments. Fundamentally I guess this is similar to the [docker image](https://hub.docker.com/r/willmclaren/ensembl-vep/) that we produce; however dockerhub's triggers allow us to write once and leave as the image gets updated every time a new branch or tag is created on github. It might be you can use the [Dockerfile](https://github.com/Ensembl/ensembl-vep/blob/release/88/docker/Dockerfile) for this as a guide, or perhaps [the build config we use for Travis](https://github.com/Ensembl/ensembl-vep/blob/release/88/.travis.yml).

Regarding picking up Bio::DB::HTS, if it is in the PERL5LIB then it should work OK. Otherwise you can modify this variable to point to the location of Bio::DB::HTS. Again, look at the Dockerfile for hints on this.

I can't seem to get conda to install the recipe; probably this is a generic conda issue rather than one related to the package itself. I installed [miniconda](https://conda.io/miniconda.html) on my mac laptop, then ran:

```
$ conda config --add channels conda-forge
$ conda config --add channels defaults
Warning: 'defaults' already in 'channels' list, moving to the top
$ conda config --add channels bioconda
williams-air:~ will$ conda install ensembl-vep
Fetching package metadata .............


PackageNotFoundError: Package not found: Conda could not find '
```

**Comment by matthdsm** [comment]
Hi Will,

Thanks for the pointers! I'll look into it.
The facts vep won't install on your mac is because the package was only built for linux systems, and skipped osx.
It's possible let the package be built for OSX too, but I chose not, because of some issues I hadn't had the time to deal with.
Good thing is, bioconda accepts PR's from just about anyone and the community is really responsive, so feel free to go ahead and change stuff.

Thanks again
Cheers
M
