### ISSUE TITLE
Haplosaurus truncates sequence information if one haplotype is stop-gain

### ISSUE THREAD

**Issue by LukeGoodsell** [Ensembl/ensembl-vep#510]
Hi,

I've found that when a variant introduces a stop gain in one haplotype, Haplosaurus correctly reports the mutant haplotype having a truncated sequence with a stop codon at the end, but also truncates output of the other haplotype sequence. I would expect (and in fact need) that the whole sequence of both haplotypes be provided. I understand that if the case of a stop-loss event this would be beyond the scope of Haplosaurus, but this seems like a design decision.

Example:

    sed 's/ \{2,\}/\t/g' > example.vcf <<'EOF'
    ##fileformat=VCFv4.2
    ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotypes">
    #CHROM  POS       ID                     REF  ALT    QUAL  FILTER  INFO                    FORMAT  sample
    chr7    50367277  chr7:50367277_T>TCCCC  T    TCCCC  40    PASS    mutation_type=somatic   GT      0|1
    chr7    50367271  chr7:50367271_G>C      G    C      40    PASS    mutation_type=germline  GT      1|0
    EOF
    
    haplo \
            --input_file example.vcf \
            --output_file example_haplo.json \
            --assembly GRCh37 \
            --refseq \
            --json \
            --database \
            --port 3337 \
            --transcript_filter "stable_id match NM_001220765.1"
    
    jq -rs  '[  .[]
                    | [.cds_haplotypes, .protein_haplotypes]
                    | transpose
                    | map({"cds": .[0], "prot": .[1]})[]
                    | { "cds_name":.cds.name, "prot_name":.prot.name, "prot_seq":.prot.seq }
             ]
                | (.[0] | to_entries | map(.key)), (.[] | [.[]]) 
                | @csv
            ' \
            example_haplo.json \
        | csvlook --max-column-width 55

| cds_name                | prot_name                                               | prot_seq                                              |
| ----------------------- | ------------------------------------------------------- | ----------------------------------------------------- |
| NM_001220765.1:85ins{4} | NP_001207694.1:29delE,31M>R,32ins{4},37I>R,38insG,40... | MDADEGQDMSQVSGKESPPVSDTPDEGDPRAHADPRGPLHHLGRTAKLQE*   |
| NM_001220765.1:78G>C    | NP_001207694.1:26E>D                                    | MDADEGQDMSQVSGKESPPVSDTPDDGDEPMPIPEDLSTTSGGQQSSKSDRVV |

I am using e!91 with a local cache, but have provided the commands using the public database so you can reproduce the results.

**Comment by at7** [comment]
Hi @LukeGoodsell ,
first of all thank you for your excellent description of the problem with added examples and output. This really helps us to figure out what is wrong. When you say `but also truncates output of the other haplotype sequence` do you mean that NM_001220765.1:78G>C's protein sequence ends after `..RVV`? In that case: Haplosaurus doesn't decide the length of the protein sequence based on a truncating variant in a previous haplotype. The truncated protein sequence is the result of mismatches between the transcript and the reference sequence. The whole problem and how we deal with it is explained [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq). The bam file contains corrections for NM_001220765.2 but not for NM_001220765.1 which is why you can see the full protein length for NM_001220765.2 in your output. Please let me know if you have more questions or if your question was addressing something else.
Thanks,
Anja

**Comment by LukeGoodsell** [comment]
Thanks Anna. I'd misunderstood the output but your answer is very helpful.
