### ISSUE TITLE
vep did not output hgvsp in offline mode

### ISSUE THREAD

**Issue by lituan** [Ensembl/ensembl-vep#526]
Hi

there is a variant chr22-30077427-GAG-GGA (GRCh37), in VEP web app, it has HGVSp (http://grch37.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=w1rgYG22e6sonwTD-5461915), but in offline mode, it did not has HGVSp

I use conda to install ensembl-vep 97, and cache version is homo_sapiens_refseq_vep_97_GRCh37.tar.gz

**Comment by dglemos** [comment]
Hi @lituan,

What command are you using to run vep in offline mode? 
To add HGVS when using `--offline `or `--cache` you must use a fasta file (`--fasta`), vep uses this file to generate HGVS.

**Comment by lituan** [comment]
Hi 

the command is as following:

vep --cache --dir_cache  /vep97_data/cache  --assembly GRCh37 --offline --refseq --input_file test.vcf --tab -o test.vep.tsv --force_overwrite --hgvs --fasta human_g1k_v37.fasta

I put two variants in test.vcf
chr22   30077427        .       GAG     GGA     .       .       .
chr22   30077428        .       AG      GA      .       .       .

these two variants are same variants, vep gives hgvsp for the second variant but not for the first variant

**Comment by dglemos** [comment]
Thank you for the examples. 
You're right, the output should be the same but vep doesn't parse the first variant as it should. We will look into that. 

Thanks,
Diana

**Comment by dglemos** [comment]
Hi @lituan,

There's one flag `--minimal` which will normalise the variant input before consequence and HGVS calculations. If you run your examples with this flag, both variants are interpreted as being the same and you get the correct output. 
You can read more about this [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html).

**Comment by chumawinnie** [comment]
### Issue with VEP Annotation in Offline Mode - `--hgvs` Disabled Due to Missing FASTA File

Hi nf-core/sarek community,

I recently encountered an issue while running the VEP annotation step in my nf-core/sarek pipeline. Below is the initial code I used to run the pipeline:

```bash
nextflow run nf-core/sarek -profile docker \
  --input samplesheet.csv \
  --outdir /home/obiorach/test-work-sarek/WES-test-result \
  --genome hg19 \
  --dbsnp /home/obiorach/whole-Exon-single-seq/ref-genome/known_sites.vcf/dbsnp_138.hg19.vcf.gz \
  --known_indels /home/obiorach/whole-Exon-single-seq/ref-genome/known_indels.vcf/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf.gz \
  --max_cpus 20 \
  --max_memory '30 GB' \
  --wes \
  --intervals /home/obiorach/whole-Exon-single-seq/ref-genome/exom_targets.bed/HyperExomeV2_primary_targets.hg19.bed \
  --tools mutect2,strelka,vep \
  --pon /home/obiorach/whole-Exon-single-seq/ref-genome/panel-of-normal/updated_Mutect2-exome-panel_vcf.vcf.gz \
  --germline_resource /home/obiorach/whole-Exon-single-seq/ref-genome/germline-resource/renamed_gnomad.vcf.gz \
  --vep_cache /home/obiorach/datasets/auxiliary_files_and_databases/VEP_cache \
  --vep_species homo_sapiens \
  --vep_genome GRCh37 \
  --vep_cache_version 106 \
  -c custom.config \
  -resume
```

During the VEP annotation step, here was the execution following command:

```bash
vep \
  -i Normal.strelka.variants.vcf.gz \
  -o Normal.strelka.variants_VEP.ann.vcf.gz \
  --stats_file Normal.strelka.variants_VEP.ann.summary.html \
  --vcf --everything --filter_common --per_gene --total_length --offline --format vcf \
  --compress_output bgzip \
  --assembly GRCh37 \
  --species homo_sapiens \
  --cache \
  --cache_version 106 \
  --dir_cache ${PWD}/VEP_cache \
  --fork 6
```

However, I received the following message:

```
2024-08-18 21:45:32 - INFO: Disabling --hgvs; using --offline and no FASTA file found
```

It seems that the `--hgvs` option is being disabled because I’m running VEP in offline mode without providing a reference FASTA file. This behavior was unexpected, and I’m not sure how critical it is for my downstream analysis.

### My Questions:
1. **Is providing a FASTA file mandatory for accurate VEP annotations in offline mode, specifically when `--hgvs` is needed?**
2. **What are the potential impacts of not having HGVS annotations on the final output?**
3. **Is there a recommended solution for this within the nf-core/sarek workflow, or do I need to manually include a FASTA file in the VEP command?**

I’m using GRCh37 as my reference genome and have the VEP cache properly set up. Any guidance or suggestions on how to resolve this issue or any workarounds that might be available would be greatly appreciated.

Thank you for your help!

Best regards,
