### ISSUE TITLE
VEP for structural variants: how is insertion consequence calculated? 

### ISSUE THREAD

**Issue by CWYuan08** [Ensembl/ensembl-vep#529]
Hi there,
I know VEP only takes in coordinates and SVTYPE, how does this work for insertions? Since the alignments are relative to the reference, if the variant callers report a local point (i.e. start and end positions are nearly the same), how would VEP knows about the insertion size and consequences? The variant caller we use report a range, I guess this is even less reliable? 

Thank you again 
WIth regards
Ulrika

**Comment by dglemos** [comment]
VEP predictions for SVs are limited at the moment. As you said SVs are defined by a coordinate range and a SVTYPE this means that the effects of a structural variant are calculated from a structural perspective (rather than a sequence). For all SVTYPEs, including insertions, VEP only identifies overlapping features based on the input coordinates.  

There is not much documentation about SVs in VEP but you can see read [here](https://www.ensembl.org/info/docs/tools/vep/vep_formats.html#sv) about input formats and see [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_example.html#StructVar) a few examples.

**Comment by dglemos** [comment]
I'm going to close this issue now. If you have any other questions please feel free to reopen it.
