### ISSUE TITLE
Inframe insertions not being annotated correctly

### ISSUE THREAD

**Issue by csweeney225** [Ensembl/ensembl-vep#534]
I am trying to run pVACseq to predict MHC class I and class II binding affinities. I have created my VCF
files using the hg38 assembly and then use VEP with GRCh38 to annotate variants. 

Although most variants appear to be annotated correctly, inframe deletions are not - reference bases from the VCF don't match Ensembl transcripts at the positions. Due to this, I am unable to run pVACseq for these variants. I have contacted the developer of this package who suggested the problem lies with VEP annotations and that I should ask for your advice. I have attached a VEP-annotated VCF as an example.

[OX1072_patient_vep.txt](https://github.com/Ensembl/ensembl-vep/files/3401765/OX1072_patient_vep.txt)

**Comment by aparton** [comment]
Hi,

The value returned by VEP in the REF column of the VCF output is taken directly from the users input data, so I suspect that this is where the issue lies. If you don't believe this to be the case, could you please send me your input data for the variants in question?

There are a couple of potential workarounds to this. The flag `--check_ref` will compare the given reference sequence to the underlying transcript sequence and skip variants where they do not match. The flag `--use transcript_ref` will tell VEP to use the reference alleles from the underlying transcript, however the REF value of the VCF output will still be the given reference. More information on these flags can be found here: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any other questions or comments, please feel free to reopen it.

Kind Regards,
Andrew
