### ISSUE TITLE
ERROR: Failed last resort of using HTTP::Tiny to download

### ISSUE THREAD

**Issue by 694376965** [Ensembl/ensembl-vep#566]
hello, everyone!
when I input the command 'perl INSTALL.pl',  the following errors were reported:

http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#requirements
ERROR: Failed last resort of using HTTP::Tiny to download https://api.github.com/repos/Ensembl/ensembl-vep

It means that it cannot download things by 'HTTP::Tiny' from the address 
'https://api.github.com/repos/Ensembl/ensembl-vep'.
but it appears that the 'HTTP::Tiny' can work well when I install 'Archive::Zip' and 'DBI'

Does anyone have the same problem? 
I am looking forward to your help!
 Thank you very much!

**Comment by ens-lgil** [comment]
Dear @694376965,

This might be due to the GitHub API rate limit: 60 requests/hour/IP (https://developer.github.com/v3/#rate-limiting)
You should be able to monitor it, using the following command: 
```
curl -i https://api.github.com/rate_limit
```
and I got this in return:
```
HTTP/1.1 200 OK
Date: Mon, 19 Aug 2019 10:18:26 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 6606
Server: GitHub.com
Status: 200 OK
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59
X-RateLimit-Reset: 1566213506
...
```

Please, could you try to run the `perl INSTALL.pl` command when the `X-RateLimit-Remaining` is above 1 ? 

Best regards,
Laurent

**Comment by 694376965** [comment]
According to the way you told me, the problem was solved.
Thank you very much!

**Comment by ens-lgil** [comment]
I am closing this issue, but if you have any more questions please feel free to reopen it.

Best regards,
Laurent
