### ISSUE TITLE
Cannot Install Ensembl VEP in windows 10

### ISSUE THREAD

**Issue by Nch77** [Ensembl/ensembl-vep#585]
Hi, 
I am having some troubles in installing Ensembl VEP.
First, I can´t see the Ensembl Desktop. I see the terminal but i cannot write in it.
Second, wen i run: 
perl install.pl
It gave me this error message: 

"which" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"which" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"which" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"which" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"which" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
LWP::Simple failed (500), trying to fetch using HTTP::Tiny
ERROR: Failed last resort of using HTTP::Tiny to download https://api.github.com/repos/Ensembl/ensembl-vep

thanks for your help!!!

**Comment by aparton** [comment]
Hi,

Are you using the Ubuntu shell within Windows 10, or are you using a virtual machine?

It looks as if your terminal window doesn’t have ‘which’ installed. If you’re using Ubuntu, then you can install this with ’sudo apt-get install which’. If you’re using the virtual machine, VEP should already be installed.

Kind Regards,
Andrew

**Comment by Nch77** [comment]
Hi Andrew,
Thank you very much for you answear.
I am using a Oracle Virtual Machine.
But i have installed Ubuntu in the same computer.
I am trying to use VEP in the virtual machine.
Thanks for your help.
Bests,
Ignacio

**Comment by aparton** [comment]
Hi Ignacio,

Ensembl has a pre-prepared Virtual Machine that may be useful to you: https://www.ensembl.org/info/data/virtual_machine.html <https://www.ensembl.org/info/data/virtual_machine.html> - using this VM would save you the time of having to install and configure VEP on your own VM. Alternatively, we also have a docker image that would aid with installation if that’s something you’d be interested in using.

However, if you would prefer to use your own virtual machine then I’m happy to help you debug. Were you able to install ‘which’ on your VM?

Kind Regards,
Andrew

**Comment by Nch77** [comment]
Hi Andrew,
Thank you very much for your help.
The Virtual Machine that I had installed, is the VM of Ensembl. The same
link that you wrote.
I have followed the instruccions in this web and i can not see the ensembl
desktop.
Bests,
Ignacio.

**Comment by aparton** [comment]
Hi Ignacio,

To help me debug this issue, I have a few more questions about your current setup:

1. Can you see the Ensembl desktop in the list of your virtual machines given to you by VirtualBox?

2. When you start the virtual machine, are you able to see the Ubuntu Desktop? If not, what happens when you click start?

3. Are you able to run ./verify_installation as described in https://www.ensembl.org/info/data/virtual_machine.html <https://www.ensembl.org/info/data/virtual_machine.html>?

Kind Regards,
Andrew

**Comment by Nch77** [comment]
Hi Andrew,
thank you very much for your help.
Here are my answers:

1. Can you see the Ensembl desktop in the list of your virtual machines
given to you by VirtualBox?
*Yes*

2. When you start the virtual machine, are you able to see the Ubuntu
Desktop? If not, what happens when you click start?
*I can see the Ubuntu desktop, but i cannot write anything there.*

3. Are you able to run ./verify_installation as described in
https://www.ensembl.org/info/data/virtual_machine.html <
https://www.ensembl.org/info/data/virtual_machine.html>?
*I can´t verify the installation because i can´t write in the ubuntu
desktop and i can´t acces to the terminal icon on the panel on the left.*

I don´t know why i can´t send you a print screen of the VM, but what i
finally see is the Ensmbl - Oracle VM VirtualBox totally black with the
cursor blinking, but it don´t allow me to type.

Kind regards.
Ignacio.

**Comment by aparton** [comment]
Hi Ignacio,

Unfortunately this sounds like a VirtualBox problem rather than a VEP problem, so my ability to help you is limited. 

A couple of thoughts below:

- Is the memory provided to the VM sufficient?
- The VBox log files may have some insight into what’s going on: http://spacetech.dk/virtualbox-log-files-location.html <http://spacetech.dk/virtualbox-log-files-location.html>
- If you continue to have VM issues, it may be worth attempting to setup our Docker image - https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker <https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker>

Apologies that I couldn’t do more to help.

Kind Regards,
Andrew

**Comment by Nch77** [comment]
Hi Andrew,
thank you very much for your help.
I will try to use the Docker image.
Kind regards.
Ignacio.
