### ISSUE TITLE
Criteria for selecting only one, if there are multiple variations in same locus. (--pick option)

### ISSUE THREAD

**Issue by QANGFQ** [Ensembl/ensembl-vep#595]
Hi,

When using VEP --pick option, if there are multiple variations in same locus, could you tell me the criteria to select only one consequence?

For example,
variant : chr1	901806	rs2879815	G	C,GC
There is only GC(alternative allele) variant in VEP output.

Best regards,
QANGFQ

**Comment by dglemos** [comment]
Hi @QANGFQ,
In the case of multiple ALT alleles, you can use `--pick_allele` which chooses one consequence per variant allele. You can read more about all the options [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick). 

Best regards,
Diana

**Comment by QANGFQ** [comment]
Hi, Diana

Thank you for your reply but just printing each consequence per line using --pick_allele isn't what I want. 

I want to select most severe one consequence per variant having multiple alternative alleles on same locus in vcf format but using --most_severe option dosen't includes several informations (ex: GENE SYMBOL, etc).

--pick option makes it possible to select one per variant having multiple alternative alleles but I don't know whether that one is most severe.

Of course, I've already seen --pick option description and an dordered set of criteria at https://asia.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick

However, the criteria do not seem to correspond to the situation of multiple alternative alleles, so I asked you criteria in a previous post.

Best regards,
QANGFQ

**Comment by dglemos** [comment]
Thank you for the detailed explanation. The --pick option doesn't select by most severe consequence, this option picks one annotation per variant using an ordered set of criteria such as the canonical status of the transcript and the APPRIS annotation (you can see the complete list and the order in the link above). 
To get the most severe consequence per variant you need to use the option --most_severe but in this case, as you said, the output only contains the consequence and all the other transcript-specific columns will be left blank. Unfortunately, at this moment we don't have an option to get the most severe consequence and output all the other data columns.

**Comment by willmclaren** [comment]
I'm not exactly sure if this would give you what you want, but you can combine `--pick` with `--pick_order rank`; this would prioritise the observed effect with the most severe consequence.

It would also be prudent to add some additional fields to the `--pick_order` flag, for example: `--pick_order rank,canonical,appris,tsl` as this will ask VEP to select sensibly among multiple observed effects with the same consequence.

Please do heed [the warnings](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#pick) when doing this, though. The reason VEP does not do this by default is that frequently the most severe consequence will be observed in a transcript or gene that is unlikely to be expressed or the "real" transcript.

The best approach is to make use of `--flag_pick`  instead of `--pick`, as this allows you to post-filter your output to identify those picked without losing the data supporting it.

**Comment by QANGFQ** [comment]
Thank you for the detailed explanation. Your reply was helpful to me. 

Best regards,
QANGFQ
