### ISSUE TITLE
Multiple runs with STDOUT throws error about Stats file already exists

### ISSUE THREAD

**Issue by JohnMCMa** [Ensembl/ensembl-vep#60]
The running environment is RHEL6 with perl 5.22.1, BioPerl 1.6.901 and VEP version 89.4. The VEP is called like the following: `./ensembl-vep/vep -i [redacted] --offline --cache --assembly GRCh37 --pick -o stdout`. After outputting the appropriate VEP result to STDOUT, it throws an error:
````
-------------------- EXCEPTION --------------------
MSG: ERROR: Stats file stdout_summary.html already exists. Specify a different output file with --stats_file or overwrite existing file with --force_overwrite

STACK Bio::EnsEMBL::VEP::BaseRunner::get_stats_file_handle /scratch/lym_myl_rsch/mma/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:273
STACK Bio::EnsEMBL::VEP::BaseRunner::dump_stats /scratch/lym_myl_rsch/mma/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:307
STACK Bio::EnsEMBL::VEP::Runner::finish /scratch/lym_myl_rsch/mma/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:161
STACK Bio::EnsEMBL::VEP::Runner::run /scratch/lym_myl_rsch/mma/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:193
STACK toplevel ./ensembl-vep/vep:211
Date (localtime)    = Thu Jun 29 14:23:23 2017
Ensembl API version = 89
---------------------------------------------------
````
I think it's a problem of not turning on `no_stats` when the STDOUT as output. I'll probably write a fix for this.

**Comment by willmclaren** [comment]
I'm not sure I'd agree this is a bug, more of an annoyance if you don't remember to set `--stats_file` or `--force_overwrite`, in that the filehandle open doesn't happen until the end of the run?

Or perhaps I'm misunderstanding?

**Comment by willmclaren** [comment]
I've put in [this change](https://github.com/Ensembl/ensembl-vep/commit/0013811175d89a991e6d883c43ea1f930dbd8a5b) that moves the file handle to the initiation stage so that you'll get the exit before the run starts.

It is a change in behaviour rather than a bug fix, so I will leave it just on master for now and it will become release code in release/90.

In the meantime you may use `--no_stats`, `--stats_file` or `--force_overwrite` to work around your issue.
