### ISSUE TITLE
VEP Results for Most Severe Consequence

### ISSUE THREAD

**Issue by MatthewPearsonRA** [Ensembl/ensembl-vep#662]
## Describe the issue
Using the VEP web interface for trying to find the "most severe consequence per variant" it returns all the consequences for the given variants, instead of returning only the most severe consequence for each given variant.

### Data files
Input:
rs1018434
rs1018430
rs1003878
Output Attached: 
[rVxf3frVkFXc43bc.txt](https://github.com/Ensembl/ensembl-vep/files/3956843/rVxf3frVkFXc43bc.txt)

**Comment by aparton** [comment]
Hi,

Thanks for this report. The --most_severe functionality provides a single consequence by ranking all consequences across all transcripts overlapped by the variant at a particular location. All transcript-specific columns are then left blank.

Each of the 3 variants you have provided map to multiple locations on the genome. While we normally exclude these variants from our output due to this ambiguity, if they are provided as an input then VEP will provide annotations for each genomic location that the variant maps to. For variants of this type, providing a line of output for each location that the variant maps to is expected behaviour. 

If you have any more questions, please don’t hesitate to ask.

Kind Regards,
Andrew
