### ISSUE TITLE
Gene symbol missing in VEP output

### ISSUE THREAD

**Issue by sabrunel** [Ensembl/ensembl-vep#667]
## Describe the issue
Gene symbol is missing for RefSeq transcripts on specific genes (eg. SCN2A, SYNJ1) when using the latest VEP release via both command lines (on Refseq cache) and the web interface.

## Additional information

We routinely use VEP release 96 for vcf annotation and initially encountered the bug on a SCN2A variant (chr2:g.166165305G>A) when running the command line below. We since replicated it locally with a newly installed release 98.

As for the web interface, we explored several levels of downsampling around chr2:g.166165305 in our input file and used the following options:
` ./vep --af --appris --biotype --buffer_size 500 --check_existing --distance 5000 --mane --polyphen b --pubmed --regulatory --sift b --species homo_sapiens --symbol --transcript_version --tsl --cache --input_file [input_data] --output_file [output_file] --port 3337`

with and without the `--refseq cache`.

While gene symbol was found for Ensembl transcripts (outside of --refseq queries),  it was consistently missing in RefSeq transcripts **except** when the input vcf only contained a single variant from SNC2A.

![missing_gene_symbol](https://user-images.githubusercontent.com/59365424/71588446-cc510b80-2b21-11ea-8696-6b3cb2831531.png)

Thanks in advance for your help!
Kind regards,
Samantha

### System
- VEP version: 96
- VEP Cache version: 96
- Perl version: perl-5.26.1
- OS: CentOS 7
- tabix installed : yes

### Full VEP command line
```
/resources/ensembl-vep/vep -i /data/analysis/25ff6df2-04f7-4116-bc1b-4fd4d446c6c9/output_files/variants.vcf.crossdb --sift b --polyphen b --offline --cache --fork 4 --dir_cache /data/resources/human/GRCh37/index/vep --buffer_size 5000 --vcf -o /data/analysis/25ff6df2-04f7-4116-bc1b-4fd4d446c6c9/output_files/variants.vcf.annotated --fasta /data/resources/human/GRCh37/fasta/GRCh37.fa --refseq --cache_version 96 --no_stats --no_progress --force_overwrite --ccds --uniprot --hgvs --symbol --numbers --biotype --gene_phenotype --variant_class --domains --dir_plugins /data/resources/human/VEP_plugins --plugin MaxEntScan,/data/resources/human/VEP_plugins/MaxEntScan --plugin GeneSplicer,/data/resources/human/VEP_plugins/GeneSplicer/bin/linux/genesplicer,/data/resources/human/VEP_plugins/GeneSplicer/human,context=200,tmpdir=/tmp --plugin dbNSFP,/data/resources/human/VEP_plugins/dbNSFP/GRCh37/dbNSFP.txt.gz,cds_strand,refcodon,codonpos,codon_degeneracy,Ancestral_allele,AltaiNeandertal,Denisova,Ensembl_geneid,Ensembl_transcriptid,Ensembl_proteinid,aapos,SIFT_score,SIFT_converted_rankscore,SIFT_pred,Uniprot_acc_Polyphen2,Uniprot_id_Polyphen2,Uniprot_aapos_Polyphen2,Polyphen2_HDIV_score,Polyphen2_HDIV_rankscore,Polyphen2_HDIV_pred,Polyphen2_HVAR_score,Polyphen2_HVAR_rankscore,Polyphen2_HVAR_pred,LRT_score,LRT_converted_rankscore,LRT_pred,LRT_Omega,MutationTaster_score,MutationTaster_converted_rankscore,MutationTaster_pred,MutationTaster_model,MutationTaster_AAE,MutationAssessor_UniprotID,MutationAssessor_variant,MutationAssessor_score,MutationAssessor_score_rankscore,MutationAssessor_pred,FATHMM_score,FATHMM_converted_rankscore,FATHMM_pred,PROVEAN_score,PROVEAN_converted_rankscore,PROVEAN_pred,Transcript_id_VEST3,Transcript_var_VEST3,VEST3_score,VEST3_rankscore,MetaSVM_score,MetaSVM_rankscore,MetaSVM_pred,MetaLR_score,MetaLR_rankscore,MetaLR_pred,Reliability_index,M-CAP_score,M-CAP_rankscore,M-CAP_pred,REVEL_score,REVEL_rankscore,MutPred_score,MutPred_rankscore,MutPred_protID,MutPred_AAchange,MutPred_Top5features,CADD_raw,CADD_raw_rankscore,CADD_phred,DANN_score,DANN_rankscore,fathmm-MKL_coding_score,fathmm-MKL_coding_rankscore,fathmm-MKL_coding_pred,fathmm-MKL_coding_group,Eigen_coding_or_noncoding,Eigen-raw,Eigen-phred,Eigen-PC-raw,Eigen-PC-phred,Eigen-PC-raw_rankscore,GenoCanyon_score,GenoCanyon_score_rankscore,integrated_fitCons_score,integrated_fitCons_score_rankscore,integrated_confidence_value,GM12878_fitCons_score,GM12878_fitCons_score_rankscore,GM12878_confidence_value,H1-hESC_fitCons_score,H1-hESC_fitCons_score_rankscore,H1-hESC_confidence_value,HUVEC_fitCons_score,HUVEC_fitCons_score_rankscore,HUVEC_confidence_value,GERP++_NR,GERP++_RS,GERP++_RS_rankscore,phyloP100way_vertebrate,phyloP100way_vertebrate_rankscore,phyloP20way_mammalian,phyloP20way_mammalian_rankscore,phastCons100way_vertebrate,phastCons100way_vertebrate_rankscore,phastCons20way_mammalian,phastCons20way_mammalian_rankscore,SiPhy_29way_pi,SiPhy_29way_logOdds,SiPhy_29way_logOdds_rankscore,clinvar_rs,clinvar_clnsig,clinvar_golden_stars,Interpro_domain,GTEx_V6p_gene,GTEx_V6p_tissue --plugin dbscSNV,/data/resources/human/VEP_plugins/dbscSNV/GRCh37/dbscSNV.txt.gz,GRCh37
```

### Data files
Input vcf file can be provided if needed.

**Comment by sabrunel** [comment]
Downsampled input and output files can be found at: https://gist.github.com/2c0d1bb02df8f39b7d461c26ad5a8508

**Comment by aparton** [comment]
Hi,

Thanks for this report. I've been able to reproduce the bug at this end. We'll look into getting a fix in place and I'll keep you up to date on its progress.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I've looked into this issue over the last couple of days. In short, this is an issue that we expect to fix with our planned GRCh37 projected RefSeq annotations update for release 100 - currently scheduled for release in early April.

In a little more detail, this issue appears only when you're using the GRCh37 data with the flags --cache and --refseq, and for specific transcripts. In human, we import RefSeq transcripts from multiple sources, creating duplicates in the database. While these duplicates have the same transcript stable ids (i.e. NM_* identifiers), infrequently they will differ in other ways. On these occasions, normally we prioritise our higher quality transcript sets. 

However in this case, VEP is using our older transcript set that does not have gene symbol information attached. VEP caches contain files representing genomic regions split into chunks to allow for faster lookup of overlapping features, with transcripts that overlap multiple chunks included within each relevant file. SNC2A has duplicate transcripts included within the cache file, however while the lower-quality transcripts are included within the earlier region chunk, the higher quality ones are not. This leads to VEP caching the lower-quality transcript data, and as such the gene symbol information is missing.

This is an issue that we expect to fix as part of our larger GRCh37 update for release 100. Unfortunately the only available workaround currently would be to rerun variants on these genes separately. 

Thanks again for bringing this issue to our attention. I'll get in touch and let you know when the fix is in place.

Kind Regards,
Andrew

**Comment by sabrunel** [comment]
Hi,

Thank you for your detailed reply, we'll be looking forward to the next release!

Kind regards,
Samantha

**Comment by aparton** [comment]
Hi @sabrunel,

Just to let you know, Ensembl 100 has now been released, so this issue should now be resolved. If you still see any issues, please let us know and we'll see what we can do to help.

Kind Regards,
Andrew
