### ISSUE TITLE
Why is the Dockerfile so complicated?

### ISSUE THREAD

**Issue by anderspitman** [Ensembl/ensembl-vep#681]
Based on the installation instructions, I would expect the Dockerfile to essentially be a thin wrapper around `git clone` and `perl INSTALL.pl`, but it seems to be doing way more than that. How much of it is necessary if I wanted to make my own image? I'm specifically using singularity, not Docker.

**Comment by aparton** [comment]
Hi @anderspitman,

Our Docker image is designed to be as lightweight as possible, while still providing full VEP functionality. Modules that are necessary only for installation are removed to reduce the file size of the produced image. Additional modules such as ensembl-xs and Bio::DB::BigFile are included within the Docker image in order to optimise runtimes and allow users to work with bigWig files.

That said, if you wanted to include VEP within your own Docker/Singularity image then using `perl INSTALL.pl` would be absolutely fine in most cases.

If you have any more questions, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by serge2016** [comment]
Similar question: https://github.com/Ensembl/ensembl-vep/issues/451

**Comment by anderspitman** [comment]
Excellent, thanks for the explanation and linked issue.
