### ISSUE TITLE
Argument "" isn't numeric in numeric eq (==) at VEP.pm

### ISSUE THREAD

**Issue by jeongmeani** [Ensembl/ensembl-vep#683]
Hi, 
now i'm analyzing WES data.
and i have run Mutect then did annotation using vep.

but it returns message

"" Argument "" isn't numeric in numeric eq (==) at /data/tools/VEP_install/ensembl-vep-release-98/modules/Bio/EnsEMBL/VEP/OutputFactory/VCF.pm line 373. ""

how can i fix this?

my code is
`vep --input_file TNB_33.mutect.filtered.vcf.gz --output_file test.annot2.vep.vcf --format vcf --vcf --symbol --terms SO --tsl --hgvs --fasta /data/ref/hg19/hg19.fa -offline --plugin Downstream --plugin Wildtype --dir_cache /data/ref/vep/ --assembly GRCh37 --refseq`

Thanks!

**Comment by aparton** [comment]
Hi,

Could you please run your query without the Wildtype and Downstream plugins, and let me know if this reproduces the message? If it does, could you please send me a copy of your input file so I can take a closer look?

Kind Regards,
Andrew

**Comment by jeongmeani** [comment]
i ran my query without the Wildtype and Downstream plugins, and it didn't print error message like above!
was there a problem about plugin?

Thank you!

Best Regards.
Jeongmin

**Comment by aparton** [comment]
Hi,

Excellent, thanks for this. The Downstream plugin was created by us, however Wildtype was developed by a different group and as such you would need to contact them regarding issues if it transpires that this plugin was causing the issue.

Could you please try running your analyses again with only the Downstream plugin to check which plugin it is that's causing the issue?

Kind Regards,
Andrew

**Comment by jeongmeani** [comment]
OK!
The run is completed.

With Downstream plugin, it gives message.
and what would i do-?

Thank you!

Best regards
Jeongmin

**Comment by aparton** [comment]
Hi,

Could you please send me a copy of your input file so I can take a closer look? If it's too large to be sent through here, please email a copy to helpdesk@ensembl.org

Kind Regards,
Andrew

**Comment by Alasiriab2** [comment]
I'm facing the same issue right now LoF plugin.

**Comment by aparton** [comment]
Hi @Alasiriab2,

Thanks for this report. Could you please send me a copy of your input file and I can take a closer look?

Kind Regards,
Andrew

**Comment by jeongmeani** [comment]
sorry for late reply.
OK!
i send the input file now!

Best Regards.
Jeongmin

**Comment by jeongmeani** [comment]
Hi,

the day before yesterday, i sent you the input vcf file that occurs warning message.
but you don't read the mail so far.
so i guess this mail is sent to your spam.
could you please this mail?

Thanks!

Best Regards.
Jeongmin

**Comment by aparton** [comment]
Hi,

Thanks for sending on the file. I'll take a look today and let you know when I know more.

Kind Regards,
Andrew

**Comment by Chitanda-Satou** [comment]
Hi, thanks for finding out the problem, dear @aparton . I'm facing the same issue in the Wildtype.pm. 
**Will this issue induce to serious problems?**

**Comment by aparton** [comment]
Hi @Chitanda-Satou,

A bugfix has just been released for this issue with Ensembl 100. Updating and running should resolve this problem.

I don't believe that this issue was causing any serious problems in older VEP, it was just a warning that was safe to ignore, however I suggest updating to the latest VEP version if possible.

Kind Regards,
Andrew

**Comment by student-t** [comment]
My command was 


    docker run -v $PWD:/data w19 vep --vcf --force_overwrite --everything --offline \
			   -i /data/CTRL-NEUZW913DKF-03734-G_1.recalibrated.haplotypeCalls.vcf.gz \
			   -o /data/output.vcf \
			   --fasta /data/Homo_sapiens.GRCh38.dna.primary_assembly.fa.bgz \
			   --plugin REVEL,/data/revel.tsv.gz     \
			   --plugin TSSDistance				     \
			   --plugin MaxEntScan,/data/fordownload \
			   --plugin GO 							 \
			   --plugin miRNA						 \
			   --plugin dbNSFP,/data/dbNSFP4.0.gz,ALL \
			   --plugin FunMotifs,/data/all_tissues.funmotifs_sorted.bed.gz,fscore

No Wildtype but the exact same message.

**Comment by kaloyan-marinov** [comment]
Hello,

May I ask for a follow-up on this issue?

It seems that I have encountered the same issue as @student-t . However, instead of `/data/dbNSFP4.0.gz`, I was using the following version of the dbNSFP plugin: ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFP4.1c.zip

Specifically, I created a Docker container and obtained access to its interactive shell by running:
```
docker run -t -i --rm \
    -v $HOME/vep_data:/opt/vep/.vep \
    ensemblorg/ensembl-vep
```
and then I executed:
```
./vep \
    --cache \
    -i /opt/vep/.vep/input/in.vcf \
    -o /opt/vep/.vep/output/out.vcf \
    --no_stats \
    --assembly GRCh37 \
    --fasta /opt/vep/.vep/homo_sapiens_refseq/100_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz \
    --refseq \
    --total_length \
    --vcf \
    --offline \
    --no_progress \
    --fork 16 \
    --plugin dbNSFP,/opt/vep/.vep/dbNSFP4.1c.gz,ALL
```
which printed the following message several times:
```
Argument "." isn't numeric in numeric eq (==) at /opt/vep/.vep/Plugins/dbNSFP.pm line 325, <__ANONIO__> line 15622.
```

(It is hard to tell if this is related but let me mention it anyway on the off-chance that it may be related - in addition to the above, after I press `CTRL + C` to terminate the interactive session in the container, I notice that the `$HOME/vep_data/output/out.vcf` file in the host environment has not been annotated with the functional prediction scores from the dbNSFP.)

Could you help me get this to work?

Thank you for your time and help.

**Comment by marionamujal** [comment]
Hello,

May I ask for a follow-up on this issue as well?
Many thanks!

**Comment by aparton** [comment]
Hi,

I believe this issue is resolved with the latest version of dbNSFP. Upgrading to v104 should fix this issue.

Kind Regards,
Andrew
