### ISSUE TITLE
filter_vep add label to FILTER field

### ISSUE THREAD

**Issue by fgvieira** [Ensembl/ensembl-vep#690]
Dear all, 

as it is now, all variants that match the filtering criteria are excluded.
Would it be possible to add an option to add (or replace) a label under the FILTER field? Like `bcftools filter` option `--soft-filter --mode +`. For example, the variant:
`1       17556   .       C       T       64.6    PASS`
would become:
`1       17556   .       C       T       64.6    failed_af`

or, if variant was:
`1       17556   .       C       T       64.6    failed_QC`
it would become:
`1       17556   .       C       T       64.6    failed_QC,failed_af`

thanks,

**Comment by dglemos** [comment]
Hi @fgvieira,

Just to know if I understand what your suggestion: you mean to change the value in 'FILTER' column (in vcf format) to a value that says this variant passed the `filter_vep` criteria?

**Comment by fgvieira** [comment]
well, change (or append) the FILTER column to some specific label if it did not match the `filter_vep` criteria.

**Comment by dglemos** [comment]
Thank you for the suggestion. We're going to look into adding this option to filter_vep.

**Comment by dglemos** [comment]
Hi @fgvieira,
Recently we added a new option to filter_vep to flag variants failing the filter instead of deleting them from the final file. This new option adds a flag to the FILTER value in the VCF file. This flag does not specify which parameters failed, it only indicates if the variant fails or not: `filter_vep_pass` means the variant passed the filter; `filter_vep_fail` variant failed the filter. 
I hope this is helpful, I'm going to close this issue but feel free to open a new one if you have more suggestions or questions. 

Best wishes,
Diana

**Comment by dglemos** [comment]
The new Ensembl release is out. For this release, we added the option `soft_filter` to filter_vep that doesn't exclude the failing variants from the output. Instead, it adds a flag to the FILTER value in the VCF. 
I'm going to close this issue now but if you have related questions feel free to reopen it. 
Best wishes,
Diana
