### ISSUE TITLE
Clinvar annotation column blank

### ISSUE THREAD

**Issue by YalithKBK** [Ensembl/ensembl-vep#747]
## Describe the issue
VEP is not filling in the CLIN_SIG column. I tried annotating the same file with snpSift and got Clinvar results for multiple entries, so I know there should be data in the column. I have tried the command with both a 1 and 0 for the --clin_sig_allele flag.

## Additional information
Downloaded (and unzipped) homo_sapiens_refseq_vep_100_GRCh37.tar.gz as my cache file. I tried to use the toplevel FASTA file but had some sort of corruption issue and went without.

### System
- VEP version: 100
- VEP Cache version: 100
- Perl version: 5.26.1
- OS: Linux Mint 19 xfce
- tabix have indexed refseq cache file, but no other tabix

### Full VEP command line
```
./vep --port 3337 --refseq --cache --dir /media/Work/Vep/ --vcf --fields "Allele,Consequence,IMPACT,SYMBOL,BIOTYPE,VARIANT_CLASS,EXON,INTRON,HGVSc,HGVSp,cDNA_position,SIFT,PolyPhen,CLIN_SIG" --variant_class --numbers --hgvs --sift b --polyphen b --clin_sig_allele 0 -a GRCh37 -i input.vcf -o output.vcf
```

### Full error message
NA

### Data files (if applicable)
NA

**Comment by aparton** [comment]
Hi @YalithKBK,

Thank you for this query, you can resolve this issue by adding the `--check_existing` flag to your VEP command. 

The `--clin_sig_allele` option was designed as a filter for `--check_existing`, telling VEP to return only allele-specific annotations rather than all annotations for a particular location. However, looking at the documentation now, then this is not clear. I'll update the documentation for our next release.

Please let me know if this resolves your issue, or if there's anything else we can do to help.

Kind Regards,
Andrew

**Comment by YalithKBK** [comment]
That did the trick. Thank you!

Yeah, the documentation was a bit confusing. I really couldn't tell what
commands I needed to get what I was looking for so I guessed. 😅

**Comment by aparton** [comment]
Excellent, I'm glad that we were able to resolve your issue.

I'm going to close this issue now, if you have any other questions please feel free to reopen it or create a new one.

Kind Regards,
Andrew
