### ISSUE TITLE
IKBKE exon variant annotated intergenic_variant

### ISSUE THREAD

**Issue by GSYongWu** [Ensembl/ensembl-vep#750]
## Describe the issue
an indel in exon of IKBKE gene, but consequence annotated intergenic_variant

## Additional information
variant: 1	206651501	.	AG	A	
annotated:
hgvsc = NM_001193321.2:c.561del
hgvsp = NP_001180250.1:p.Leu188CysfsTer60
Consequence = intergenic_variant
EXON is blank
INTRON is blank
### System
- VEP version: [100] 
- VEP Cache version: [100]
- Perl version: [5.16.3]
- OS: [redhat]
- tabix installed 1.9

### Full VEP command line
```
vep --offline --no_stats --buffer_size 10000 --fork 4 --ccds --uniprot --hgvs --symbol --shift_3prime 1 --numbers --canonical --protein --biotype --hgvsg --variant_class --shift_hgvs 1 --total_length --force_overwrite --allele_number --no_escape --vcf --dir /GPFS06/AnalysisTemp06/cln09/AIO2020/resources/public//vep/ --fasta /GPFS06/AnalysisTemp06/cln09/AIO2020/resources/public//genome/hs37d5.fa --format vcf --input_file test.vcf --output_file test.vep.vcf --refseq --use_given_ref
```

**Comment by aparton** [comment]
Hi @GSYongWu,

Thank you for this report. I've looked into this issue this afternoon, and it seems to be an edge case caused by the combination of the --shift_3prime and --vcf options.

I'll prepare a fix as quickly as possible. As a workaround in the meantime, removing the --shift_3prime option should prevent this issue from happening.

I'll let you know when there's a fix in place. Thank you for bringing this issue to our attention.

Kind Regards,
Andrew

**Comment by GSYongWu** [comment]
I really like  --shift_3prime  parameter, because I think hgvs and consequence can correspond, and I look forward to seeing you fix this bug.

**Comment by aparton** [comment]
Hi @GSYongWu,

Just to let you know, we've just release VEP 100.1, which should resolve this issue.

Kind Regards,
Andrew

**Comment by GSYongWu** [comment]
Thank you very much, very happy to see this news.
