### ISSUE TITLE
Way to customize VEP cache file

### ISSUE THREAD

**Issue by seunghun23** [Ensembl/ensembl-vep#765]
Hi, 

I am using VEP and Cache version of 100 on GRCh37 and recently got help regarding 
outdated gene name issue at issue #751. From the conversation, I learned that the current
cache has transcripts with outdated information and when I use --pick option to select only
one variant based on the selection criteria, sometimes VEP picks outdated transcripts, and I would miss variants on some important genes that I am interested in. After trying to change the pick order, I realized that it cannot completely fix the problem and was wondering if there is a way to manually modify the cache file so that I could remove information on outdated transcripts from the cache and make VEP picks a variant only from transcripts with updated gene names. Please let me know if this is possible. 

Thanks
Seunghun Han

**Comment by aparton** [comment]
Hi @seunghun23,

Unfortunately it is not possible to create a customisable cache in this manner. However, depending on exactly how you identify which transcripts are outdated, there may be a way to do this with filtering.

Instead of the --pick option, you could potentially use the --flag_pick option (https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_flag_pick), which would add a flag to the transcript chosen by the pick functionality, and retain all other transcripts as well. That would then allow you to identify which of those picked transcripts were unwanted within your analysis, and chose an appropriate replacement with filter_vep, which you can read more about here: https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html

Hopefully this will allow you to resolve your issue, although I accept that it's not ideal. If you have any other questions, please don't hesitate to ask.

Kind Regards,
Andrew

**Comment by seunghun23** [comment]
Hi Andrew, 

Thank you for your detailed answer. Following your suggestion, I ran VEP using --flag_pick option, and using the output, I tried to mimic what pick option does to select one transcript for each variant. I started with a small test dataset with 6809 transcripts for 305 unique variants, and after running my own filtering scripts using the same default order of pick option 
- 1.Canonical  2.APPRIS 3.TSL 4.Biotype(protein_coding over others) 5. CCDS status 
  6.Consequence rank 7.translated, transcript or feature length  8.MANE - 
I could reduce the original input set of transcripts down to 305 unique transcripts for 305 variants. 

However, while 301 transcripts are the ones which would have been picked using pick option, 4 of them didn't match as in the below table 
![image](https://user-images.githubusercontent.com/38226390/82988915-d88bb700-a034-11ea-93d8-3a011036c507.png)

For each pair of transcripts, one on top is what I got after my own filtering. As you can see, the two transcripts in each pair had same status for CANONICAL, APPRIS, TSL, BIOTYPE, Consequence, but they differ for CCDS, and probably for feature length. 

So my questions are 
1. is there a specific column in VEP output that VEP uses when comparing the "translated, transcript, or feature length"? In my own filter, I used the length of cDNA in the "cDNA_position" column, but in the above examples, all four pairs did not have values in the "cDNA_position" column. What you see in the last column named "Transcript_Length" are the length of each transcript I manually found from Ensembl website, and it kind of make sense why VEP would choose those transcripts labeled for "PICK" column since those have longer transcript length compared to what I got from my own filter, but I am not sure whether this was the case. 

2.Is it possible that in above cases, one transcript is chosen over another based on some criteria to compare different values in "CCDS" column? I looked up each CCDS ID on the CCDS website, and found out since which CCDS release version information on each transcript has been available. Those are what you see in the "CCDS_Release" column. One pattern I see here is that all the picked transcripts are the ones which have been released since CCDS release 1, but I doubt that this was the way VEP picked transcripts. Could you confirm this? 

Thank you so much for your help in advance

Best,
Seunghun

**Comment by aparton** [comment]
Hi Seunghun,

Thanks for your query. To answer your questions:

1) When selecting a transcript by length, `--pick` initially compares the length of the translation, and then the length of the transcript if these are identical. This does not directly correspond with any of the cDNA/Protein_position output fields, as `--pick` is choosing based off the features of the transcript rather than the location of the variant.

2) This does not appear to be the case. `--pick` will prioritise transcripts that have a CCDS status, however it will not differentiate between them. In this situation, then it will move on to the next category in the pick order to decide which transcript to select. If you have an example that contradicts this, please send it on to me and I can take a closer look.

Kind Regards,
Andrew

**Comment by seunghun23** [comment]
Hi Andrew,

According to your answer, I believe that the four transcript with Pick=1 would be selected over the other transcript due to length rather than CCDS status, and that's what I thought too. 
Following your answer for 1, where does VEP get the length of translation and transcript? Are there output fields for these values? 

Thanks,
Seunghun

**Comment by aparton** [comment]
Hi @seunghun23,

The length of the translation and transcript is taken using the underlying Ensembl API. Currently there is no way to get VEP to report this information.

For individual genes/transcripts/proteins, you can see this information on our website. For example: 
http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000139618;r=13:32315086-32400266

If you would like a way to access this information programatically, this can also be done with our REST server. For example: http://rest.ensembl.org/lookup/id/ENST00000496384?content-type=application/json;expand=1

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now. If you have any further questions, please feel free to reopen this issue or create a new one.

Kind Regards,
Andrew
