### ISSUE TITLE
Feature request: option for --pick with merged annotation to separately pick Ensembl and RefSeq transcripts

### ISSUE THREAD

**Issue by davmlaw** [Ensembl/ensembl-vep#790]
Thanks for VEP, it's great! Some groups using data I've annotated with VEP want to use RefSeq, and some Ensembl.

I tried using the merged annotations, but as Ensembl is much larger than RefSeq, almost all of the choices from --pick are for Ensembl. This means if someone only wants to use RefSeq or Ensembl (and only Ensembl or RefSeq's pick choice) I have to separately annotate them rather than being able to pull it out of the merged data.

My thoughts on the easiest way to do this would be to add new INFO fields PICK_REFSEQ and PICK_ENSEMBL and either add them automatically when using "--pick" and merged, or add new command line options --pick-ensembl and --pick-refseq

Thanks!

**Comment by ima23** [comment]
Thanks for the suggestion @davmlaw, indeed such an option would be useful and we'll look into including one as soon as possible. For a specific timeline I will need to check with the team and come back to you.
Will keep you updated on the plans.
Thanks,
Irina

**Comment by nuno-agostinho** [comment]
Hi @davmlaw,

We still have this ticket in our backlog, but we haven't been able to address it yet due to its low priority. However, we plan to incorporate these features during the upcoming VEP rewrite.

In the meantime, I will go ahead and close this issue.

If you have any further feedback, please feel free to open a new issue.

Best regards,
Nuno

**Comment by davmlaw** [comment]
@nuno-agostinho - any info on this rewrite? Are you using Perl still?
