### ISSUE TITLE
Erorr running local vep

### ISSUE THREAD

**Issue by dosshra** [Ensembl/ensembl-vep#792]
Hello
I am getting this error running vep -custom with local gff files and local genome file. VEP  runs OK with my.gff file but not with my_1.gff file. The code is `ensembl-vep/vep -i my.vcf --gff my.gff.gz --fasta my.fa -o my_vep_annotation.txt`  The error is
`Can't use an undefined value as an ARRAY reference at /home/ensembl-vep/Bio/EnsEMBL/Transcript.pm line 1613, <__ANONIO__> line 640.`

my.gff.gz file was generated using this code
`sort -k1,1 -k4,4n -k5,5n -t$'\t' my.gff3 | bgzip -c >my.gff.gz`
The tabix code was:
`tabix -p gff -C -m 14 my.gff.gz` 
flags -C and -m 14 were added because running without them generated the following error:
`Region 536882486..536882721 cannot be stored in a tbi index. Try using a csi index with min_shift = 14, n_lvls >= 6`
So I got csi index instead of tbi. As far as I understand csi is used for large genomes. My genome is > 10GB.  However, the indexing problem occurred for both gff files while one of them did not produce the error in vep.   
Thank you

**Comment by ima23** [comment]
Hi @dosshra,

I understand you have 2 gff files and vep is running ok for one and not the other.

Could you please share a small snippet of your data that would replicate the issue?
Also, if you could let me know what vep version you are using, that would also be useful for checking your case.

Thanks,
Irina

**Comment by dosshra** [comment]
Hi
I have uploaded a snippet of the data. The good gff file is chinese1A60mb.gff and the bad is chr1A1mbt.gff. The version of VAP is the last version.  The difference I could see is that in the bad file there are no definitions of exons. 
Thank you 
[snippets_vep.tar.gz](https://github.com/Ensembl/ensembl-vep/files/4874820/snippets_vep.tar.gz)

**Comment by ima23** [comment]
Hi @dosshra,

Apologies for the delay and thank you for the example data. 
Thanks to the example data I could replicate the issue and find out why one gff was running as expected and the second one was landing on that error.

The error is due to the second gff not defining any exons for mRNA transcripts. I have made a code update to highlight this in a 'warning message' and for the transcript to be skipped as VEP requires the exon models to make transcript specific annotation.
The change should be out in the next release of VEP, expected to be in a couple of weeks.

Kind regards,
Irina

**Comment by dosshra** [comment]
Thank you Irina for the reply
I will try to use a file with exons.
Hanan Sela PhD
Institute of Evolution
University of Haifa
hans@evo.haifa.ac.il
mobile: +972-50-5727458

**Comment by ima23** [comment]
Hi @dosshra,

The next release is out. I will close this ticket now. Please feel free to open it if you have other related questions.

Kind regards,
Irina
