### ISSUE TITLE
triticum_aestivum is not a valid species name

### ISSUE THREAD

**Issue by sumageb** [Ensembl/ensembl-vep#810]
Hi,
I used vep to determine the effect of variants in the wheat cultivars. I manually downloaded the cache file from ftp://ftp.ensemblgenomes.org/pub/plants/release-47/variation/vep/triticum_aestivum_vep_47_IWGSC.tar.gz. I used the following command:
./vep -i file.vcf --format "vcf" -o ~/VEP_OUTPUT/output.txt --species triticum_aestivum --cache --cache_version 47
But I received the following warning:

```
MSG: triticum_aestivum is not a valid species name (check DB and API version)
FILE: Bio/EnsEMBL/Registry.pm LINE: 1334
CALLED BY: Bio/EnsEMBL/Registry.pm  LINE: 1109
Date (localtime)    = Thu Jul 23 10:43:43 2020
Ensembl API version = 100
---------------------------------------------------

-------------------- EXCEPTION --------------------
MSG: Can not find internal name for species 'triticum_aestivum'
STACK Bio::EnsEMBL::Registry::get_adaptor /home/suma/ensembl-vep/Bio/EnsEMBL/Registry.pm:1111
STACK Bio::EnsEMBL::VEP::BaseVEP::get_adaptor /home/suma/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:308
STACK Bio::EnsEMBL::VEP::BaseVEP::get_database_assembly /home/suma/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:419
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /home/suma/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::init /home/suma/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:118
STACK Bio::EnsEMBL::VEP::Runner::run /home/suma/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel ./vep:227
Date (localtime)    = Thu Jul 23 10:43:43 2020
Ensembl API version = 100
```

I am requesting a suggestion about how I can solve this problem.

**Comment by dglemos** [comment]
Hi @sumageb,
As you are using a non-vertebrate species, you need to add the flag `--genomes` to point to the protist public database server. 

Best wishes,
Diana

**Comment by sumageb** [comment]
Thanks, Diana. I have another followup question. If I use the flag --genomes, do I need to use the cache? In the manual, I read that if I use public sever performance will be slow.

**Comment by dglemos** [comment]
If you use --genomes you don't need to use --cache but --genomes establishes a connection to the public database servers which is slower. 
The fastest way is to use VEP in offline mode. In offline mode no connection is established with the public database, the data in the cache is used for the annotation (`--offline` switches on the flag --cache).

**Comment by sumageb** [comment]
I understand your solution. For using vep offline, this species should be in the cache file if I do not use the server. So I manually downloaded the file the `~/.vep` directory. My problem is that when I used vep command, I received the above-mentioned error. Is it because vep could not catch the cache? If it happens how can vep work offline?

**Comment by dglemos** [comment]
> My problem is that when I used vep command, I received the above-mentioned error.
Did you try to run vep pointing to the right public database? `./vep -i file.vcf --format "vcf" -o ~/VEP_OUTPUT/output.txt --species triticum_aestivum --cache --cache_version 47 --genomes`

> Is it because vep could not catch the cache?
Your error is related to the database connection, not the cache. In your command vep gets the data from the cache but vep still uses a database connection to fetch data that is not in the cache like fetching reference sequence. By default, it connects to the vertebrate database (that's why your error says the species triticum_aestivum is not found) which means you need to specify --genomes to point to the non-vertebrates database. 

> If it happens how can vep work offline?
To work offline you need to use --offline and if you provide a fasta file (--fasta) vep is going to use this file to look up reference sequence. `./vep -i file.vcf --format "vcf" -o ~/VEP_OUTPUT/output.txt --species triticum_aestivum --cache --cache_version 47 --offline --fasta Triticum_aestivum.IWGSC.dna.toplevel.fa.gz`

**Comment by sumageb** [comment]
Thank you so much for your excellent clarification.

**Comment by dglemos** [comment]
I'm glad it's clear now. I'm going to close the ticket but if you have further questions feel free to open a new ticket. 
Best wishes,
Diana
