### ISSUE TITLE
Pick Chooses Intronic Variant of Overlapping Antisense Gene Instead of Deleterious Missense Variant

### ISSUE THREAD

**Issue by DarioS** [Ensembl/ensembl-vep#819]
Why is the variant

```
9 21971112 21971112 G/A
```

assigned to the gene AL359922.1 as intron_variant,NMD_transcript_variant rather than CDKN2A as a deleterious missense_variant if I used `--pick`? The two genes are on opposite strands and overlapping. AL359922.1 has a single isoform with transcript support level 5 and most of CDKN2A's transcripts have transcript support level of 1.

**Comment by DarioS** [comment]
I believe that I figured it out. The gene AL359922.1 has only one annotated transcript isoform; ENST00000404796.3. Because there's only one, that one is confidently assigned to be the canonical APPRIS isoform and has tag `appris_principal_1`. In contrast, CDKN2A has 12 different transcripts and the highest APPRIS support is `appris_principal_4`. Therefore there is no tie, and AL359922.1's transcipt wins based on APPRIS. There is no need to go down the list of rules for `--pick` and look at transcript support level.

In this case, I think matched strand-specific RNA-seq data would be greatly helpful. It shows that all of the reads support the negative strand (red colouring), the CDKN2A strand and none of them support the AL359922.1 strand (would be blue colouring). I have [made this suggestion for VEP before](https://github.com/Ensembl/ensembl-vep/issues/685).

![image](https://user-images.githubusercontent.com/631218/89112793-96a34500-d4ab-11ea-854d-7adfb3282ab1.png)

**Comment by aparton** [comment]
Hi @DarioS,

As you've noted, the APPRIS transcript status is used to decide which transcript is selected by pick in this situation, leading to the results you see. However, there are options to change how VEP selects individual transcripts that may be useful to you:
- You can use `--pick_order` to reprioritise transcripts using alternative criteria (including TSL or consequence rank) - you find find out more about `--pick_order` here: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order
- You can use `--pick_allele_gene` which will choose one line or block of consequence data per variant allele and gene combination, which will provide a selected consequence for each variant-gene combination, rather than just an individual variant, preventing the issue that you're seeing here.

Regarding the introduction of filtering as described in #685 - thank you for the suggestion. This would be a positive feature for VEP to have, however this would also be an ambitious feature request and is not something that we expect to do in the short or medium-term. I have however added it to our backlog of things to look at in the future at an appropriate time.

If you have any further questions of suggestions, please don't hesitate to get in touch.

Kind Regards,
Andrew

**Comment by aparton** [comment]
Hi @DarioS,

I'm going to close this issue now. If you have any further questions, please feel free to reopen this issue or create a new one.

Kind Regards,
Andrew
