### ISSUE TITLE
HGVSp position is different to Protein_position

### ISSUE THREAD

**Issue by jeongmeani** [Ensembl/ensembl-vep#832]
Hi, nice to meet you.
my system is below

### System
- VEP version: 98
- VEP Cache version: 98

and i got problem getting peptide sequence of mutation.
but it seems strange of position.

for example
`chr1    240370913       rs71170718      TGCCCCCTCTACCCGGAGCGGGAATACCTCCTCC      T       0       REJECT  MVDLK=0,1,0,0,0;NUM_TOOLS=1;LC=12.8;CSQ=-|inframe_deletion|MODERATE|FMN2|ENSG00000155816|Transcript|ENST00000319653.9|protein_coding|5/18||ENST00000319653.9:c.2822_2854del|ENSP00000318884.9:p.Gly941_Ala951del|3032-3064|2802-2834|934-945|LPPLPGAGIPPP/L|`

the HGVSp position is Gly941_Ala951 but protein position is 934-945.
it looks different.

am i missing something?

and i have trivial question of interpretation of Amino_acids.

what is difference among LPPLPGAGIPPP/L and GGAG/-?
and i want to know about 'X' meaning in 'R/RX'

Briefly what is the X and dash(-) meaning in the Amino_acids part?
i search on google but i can't find any information.

Best Regards 
Jeongmin

**Comment by dglemos** [comment]
Hi Jeongmin,
> the HGVSp position is Gly941_Ala951 but protein position is 934-945.
HGVS rules require a change to be described at the 3' most position. In the meantime by default VEP reports the consequences, including the protein positions, without any shifting -> `p.934` corresponds exactly to genomic position `240370913`. 
In release 100 we introduced new flags so that VEP can optionally convert variant alleles to their most 3’ representation before consequence calculation. You can read more [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#shifting).

> what is difference among LPPLPGAGIPPP/L and GGAG/-?
Both represent deletions but with different notations, LPPLPGAGIPPP/L is a deletion of PPLPGAGIPPP and GGAG/- is a deletion of GGAG.

> 'X' meaning in 'R/RX'
X is an unspecified amino acid

**Comment by dglemos** [comment]
I'm going to close the ticket but if you have further questions feel free to open a new ticket.
Best wishes,
Diana
