### ISSUE TITLE
Missing HGVSp annotation for a variant

### ISSUE THREAD

**Issue by mikpom** [Ensembl/ensembl-vep#858]
## Describe the issue
HGVSp field is empty on a variant while it is a protein-coding transcript and a nonsense mutation (e.g. see transcript ENST00000394672 in the output file below)

### System
- VEP version: 101
- VEP Cache version: 101
- Perl version: 5.26.1
- OS: Ubuntu
- tabix installed ? yes

### Full VEP command line
```
/home/mikpom/apps/ensembl-vep-release-101/vep --force_overwrite --format vcf --polyphen b --uniprot --json --symbol --offline --cache --canonical --mane --hgvs --numbers --variant_class --allele_number --fork 4 -i dup.vcf -o dup.annot.101.vepout --dir /storage1/mikpom/data/.vep101/ -fasta /home/mikpom/.vep101/FASTA/Homo_sapiens.GRCh38.dna.toplevel.fa
```

### Data files (if applicable)
- The input file
[input.zip](https://github.com/Ensembl/ensembl-vep/files/5280070/input.zip)

- The output file
[output.zip](https://github.com/Ensembl/ensembl-vep/files/5280071/output.zip)

**Comment by dglemos** [comment]
Hi @mikpom,
The variant `chr3 56557250 T/TGGGGTAAGCA` is a duplication in the exon/intron border but its consequence is in the intron. 
By default, VEP reports the consequences exactly in the position of the duplication but this change should be described at the 3' most position. In release 100 we introduced new flags so that VEP can optionally convert variant alleles to their most 3’ representation before consequence calculation. If you use the flag `--shift_3prime 1` vep is going to right-align the variant relative to its transcripts prior to consequence calculation and for your particular case, the variant is going to be annotated as intron (as it should) instead of nonsense mutation.  
You can read more about the shifting flags [here](https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#output).
