### ISSUE TITLE
--use_transcript_ref --bam GCF_000001405.25_GRCh37.p13_knownrefseq_alns.bam

### ISSUE THREAD

**Issue by thedam** [Ensembl/ensembl-vep#951]
Hey,

When I run VEP on human merged reference (hg19), and I set option `--use_transcript_ref`, do I also need to specify this option `--bam GCF_000001405.25_GRCh37.p13_knownrefseq_alns.bam`? 
Or this bam is loaded somehow automatically from cache? Do I don't need to specify it explicitly?

Thanks

**Comment by dglemos** [comment]
Hi,

The BAM files are not automatically loaded, if you need to use BAM files to correct the transcripts models you can find documentation under 
[Correcting transcript models with BAM files](https://www.ensembl.org/info/docs/tools/vep/script/vep_other.html#refseq) 
`--bam` enables the option `--use_transcript_ref `.

If you just want to use `--use_transcript_ref ` you don't need to specify the BAM files with `--bam`.
Here is the documentation for the option `use_transcript_ref`: https://m.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_use_transcript_ref

**Comment by thedam** [comment]
Thanks for quick reply, I've read the documentation however still it's not clear for me.
So for example these commands are NOT equivalent:
`vep (...) --use_transcript_ref `
`vep (...) --bam GCF_000001405.25_GRCh37.p13_knownrefseq_alns.bam`
?
The first command enables some other "transcript model", than the second one?

**Comment by dglemos** [comment]
- `--use_transcript_ref` won't use other transcript models, it will simply force VEP to use the reference allele that is in the overlapping transcript instead of using the reference allele from your input variant. For instance, your input variant is reference = C but in the RefSeq transcript the reference is A, VEP will use the A. 
- `--bam` uses the bam files that contain alignments of RefSeq transcripts to the genome. These alignments already have been incorporated and used to correct the transcript models in the human RefSeq and merged cache files but if you want to correct transcript models on-the-fly then you run the option --bam and it will enable --use_transcript_ref too, which will force VEP to use the reference allele from the RefSeq transcript (that was corrected) instead of the reference from the input variant.

**Comment by dglemos** [comment]
I'm going to close this issue. If you have more questions feel free to open a new issue.
Best wishes,
Diana
